<div class="container">
<?php

        $btnCadastrar = $this->templateFactory->getButton("cadastrar",array('href'=>URL.'produtos/categorias/gerenciar/cadastrar'), URL.'produtos/categorias/gerenciar/cadastrar');
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnCadastrar));
    ?>
    <div class="page-header">
      <h1>Categorias</h1>
    </div>
    <div class="middle-content">
        <img src="<?=URL?>img/loading3.gif" style="display: block;  margin: auto;  width: 200px;" id="loadTable">
        <table class="dataTable rwd-table" cellspacing="0" width="100%" style="display:none">
            <thead>
                <tr>   
                    <th width="100">Código</th>
                    <th width="160">Nome</th>
                    <th width="180">Ações</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Código</th>
                    <th>Nome</th>
                    <th>Ações</th>
                </tr>
            </tfoot>
            <tbody>
            <?php
            if(!empty($categorias)):
                foreach ($categorias as $cat):
            ?>
                <tr id="<?=$cat->getId()?>">
                    <td><?=$cat->getId()?></td>
                    <td><?=$cat->getNome()?></td>
                    <td>
                        <a class="btn btn-primary btn_editar btn-sm" href="<?=URL?>produtos/categorias/gerenciar/editar/<?=$cat->getId()?>" role="button" id-record="<?=$cat->getId()?>" ><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                        <a class="btn btn-danger btn_excluir btn-sm" href="javascript:void(0)" role="button" id="<?=$cat->getId()?>" data-value="<?=status::EXCLUIDO?>" ><span class="glyphicon glyphicon-remove"></span>Excluir</a>
                    </td>
                </tr>
            <?php
                endforeach;
            endif;
            ?>
                
            </tbody>
        </table>
    </div>

</div>

<script type="text/javascript">
    $(function(){
        //DATATABLE
        var table = $('.dataTable').DataTable({
            order: [0,'asc']
        });

        //EXCLUIR
        table.$('.btn_excluir').on('click',function(){
            var id = $(this).attr('id');
            var status = $(this).data('value');
            var modalDelete = $('#modalDelete').modal('show')
            $('.btn_ok','#modalDelete').on('click', function(event) {
                $.post(url+'produtos/categoria/excluir',{id:id,status:status},function(data){
                    console.log(data)
                    if(data == true){
                        $('#modalDelete').modal('hide');
                        $('tr#'+id).hide();
                    }
                });
            });
        });


    })
</script>

