        </div>

    </div><!--wrap-->
    <footer id="footer">
    	<div class="container"><small>Start Softwares</small></div>
    </footer>
    <div id="carregando"></div>
    <div id="dialogResult"></div>

    <div class="modal fade" id="modalDelete">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Atenção!!</h4>
				</div>
				<div class="modal-body">
					<p>Deseja mesmo excluir?</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					<button type="button" class="btn btn-primary btn_ok" >Ok</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->


	<!--NOTIFICAÇÃO DE FORNECEDORES-->
	<div class="modal fade" id="modalNotificacaoFornecedores">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Atenção!! - Proximidade dos agendamento de fornecedores</h4>
				</div>
				<div class="modal-body">
					<table class="table" id="tableNotificacaoAgendaFornec">
						<thead>
							<tr>
								<th>Data do agendamento</th>
								<th>Fonecedor</th>
								<th>Título</th>
							</tr>
						</thead>

						<tbody>
<!-- 							<tr>
								<td>Data do agendamento</td>
								<td>Fonecedor</td>
								<td>Título</td>
							</th> -->
						</tbody>
					</table>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" data-dismiss="modal">Ok</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->


</body>

</html>