<?php require_once('head.phtml');?>
<?php
$menus = array(
  'dashboard'=> '',
  'funcionarios' => '',
  'fornecedores' => '',
  'produtos' => '',
  'vendas' => '',
  'caixa' => '',
  'orcamento' => '',
  'estoque' => '',
  'relatorios' => '',
  'configuracoes' => ''
  );
$pag = $this->url->getSegment(0);
if($pag == false || $pag == 'gerenciar')
  $pag = 'dashboard';

$menus[$pag] = 'active';


?>
<body>
    <div id="wrap" >
        <header class="header">
            <div class="top">
                <figure class="logo">
                    <img src="<?=URL?>skin/img/logo/logo3.png">
                </figure>


                <div class="user dropdown">
                      <a href="" class="btn btn-default dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown">
                          <figure>
                          <?php
                          $fotoFunc = (unserialize($_SESSION['user'])->getFuncionario()->getFoto() != '') ? URL.'skin/uploads/funcionarios/p/'.unserialize($_SESSION['user'])->getFuncionario()->getFoto() : URL.'skin/img/imagens/perfil-icone.png';
                          ?>
                              <img src="<?=$fotoFunc?>">
                          </figure>
                          <p class="username"><?=unserialize($_SESSION['user'])->getFuncionario()->getNome()?></p>
                      </a>
                      <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                          <li><a href="<?=URL?>login/sair">Sair</a></li>
                      </ul>
                  </div>
                </div>
                <div class="container">
                  <nav class="navbar navbar-default">
                      <div class="container-fluid">
                          <!-- Brand and toggle get grouped for better mobile display -->
                          <div class="navbar-header">
                              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                  <span class="sr-only">Toggle navigation</span>
                                  <span class="icon-bar"></span>
                                  <span class="icon-bar"></span>
                                  <span class="icon-bar"></span>
                              </button>
                              <a class="navbar-brand <?=$menus['dashboard']?>" href="<?=URL?>"><span class="glyphicons glyphicons-show-thumbnails"></span><p>Dashboard</p></a>
                          </div>

                          <!-- Collect the nav links, forms, and other content for toggling -->
                          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                              <?php
                              echo $this->menu->geraMenu();
                              ?>
                          </div><!-- /.navbar-collapse -->
                      </div><!-- /.container-fluid -->
                  </nav>
                </div>
            </header>
            
        <div class="wrap-content">

      