<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <!--[if lt IE 9]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
    <title><?=isset($titlePage) && !empty($titlePage) ? $titlePage.' - ' : '' ?> SAC - Sistema de Automação Comercial</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/bootstrap.min.css" />
    <!-- <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/normalize.css" /> -->
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/animate.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/dataTables.bootstrap.css">
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/table.css">
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/main.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/default.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/jquery.toastmessage.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/large_desktops.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/desktops.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/tablets.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/extra_small_devices.css" />
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/css/awesome-bootstrap-checkbox.css" />
    
    
    
    <link rel="stylesheet" type="text/css" href="<?=URL?>skin/js/kendoui/css/kendo.common-material.min.css" />
    <link rel="stylesheet" href="<?=URL?>skin/js/kendoui/css/kendo.default.min.css" />
    

    <meta name="robots" content="noindex, nofollow" />
    <!--[if IE]>
        <link rel="shortcut icon" href="img/favicon.ico">
    <![endif]-->
    <link rel="icon" href="<?=URL?>skin/img/favicon.png" />
    <script>
        var url = "<?=URL?>";
    </script>
    

    <script type="text/javascript" src="<?=URL?>skin/js/jquery-1.11.2.min.js"></script>
    <script type="text/javascript" src="<?=URL?>skin/js/jquery.form.js"></script>
    <script type="text/javascript" src="<?=URL?>skin/js/bootstrap.min.js"></script>
    <script src="<?=URL?>skin/js/kendoui/js/kendo.all.min.js"></script>
    <script type="text/javascript" src="<?=URL?>skin/js/jquery-ui.js"></script>
    <script type="text/javascript" src="<?=URL?>skin/js/cep.js"></script>

    <script type="text/javascript" src="<?=URL?>skin/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="<?=URL?>skin/js/dataTables.bootstrap.js"></script>
    <script type="text/javascript" src="<?=URL?>skin/js/main.js"></script>
    <script type="text/javascript" src="<?=URL?>skin/js/jquery.toastmessage.js"></script>
    <script type="text/javascript" src="<?=URL?>skin/js/jquery-barcode-last.min.js"></script>
    <script type="text/javascript" src="<?=URL?>skin/js/bootstrap-notify.min.js"></script>
	
    
</head>