<?php 
$template = new template();
?>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <?=$template->page_header('Registro não encontrado');?>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-left">
        <h3>Possíveis erros:</h3>
        <ul>
        	<li>O registro não se encontra mais no banco de dados</li>
        	<li>O registro está corrompido, poderá estar dependente de algum outro registro em falta.</li>
        </ul>
    </div>
</div>