<div class="container">
    <?php
       $btnVoltar = $this->templateFactory->getButton("voltar",array('href'=>URL.'caixa'));
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnVoltar));    ?>
    <div class="page-header">
      <h1>Caixas<small> Vendas realizadas</small></h1>
    </div>
    <section>
    	<div id="grid"></div>

    </section>
</div>

<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>

<script type="text/javascript">
$(function(){

	

$("#grid").kendoGrid({
    columns: [
    {
        filterable: false,
        field: "id",
        title: "ID",
        width: "40px",
        template: '<p>#: id#</p>'
    },
    {
        field: "data",
        title: "Data",
        width: "300px",
    },
    {
        field: "total",
        title: "Total",
        width: "100px"
    }
    // {
    //     filterable: false,
    //     field: "acoes",
    //     title: "Ações",
    //     width: "100px",
    //     template : '<a class="btn btn-primary btn_editar btn-sm pull-left" href="#:linkEditar#" data-toggle="tooltip" data-placement="top" role="button" id-record=""  title="">'
		  //               +'<span class="glyphicon glyphicon-pencil"></span>' 
		  //           +'</a>'
    // }
    ],
    filterable: {
        extra: false,
        operators: {
            string: {
                startswith: "Começa com",
                eq: "É igual a",
                neq: "Não é igual a",
                contains: "Contém"
            }
        },
        messages: {
          filter: "Filtrar",
          clear: "Limpar",
          info: "Exibir itens com valores que: "
        }
    },
    dataSource:{
        transport: {
            read: {
                // url: url+"caixa/gerenciar/getjsonvenda",
                dataType: "json"
            }
        }
    },
    pageable: {
        pageSize: 8,
        refresh: true
    },
    detailTemplate: 'Caixas abertos: <div class="grid"></div>',
    detailInit: function(e) {
        e.detailRow.find(".grid").kendoGrid({
        	dataSource: {
                data: e.data.abertos,
                pageSize: 10
            },
            columns: [
                { field: "id", title:"ID", width: "80px"},
                { field: "dateOpen", title:"Data De Abertura"},
                { field: "dateClose", title:"Data De Fechamento" },
                { field: "user", title:"Funcionário" },
                { 
                    field: "acoes", 
                    title:"Ações" ,
                    template : '<a class="btn btn-primary pull-left btn_visualizar btn-sm" href="#:linkvisualizar#" data-toggle="tooltip" data-placement="top" role="button" id="btn_visualizar" title="Visualizar">'
                                    +'<span class="glyphicons glyphicons-eye-open"></span>'
                                +'</a>'
                                +'<a class="btn btn-primary pull-left btn_fechar btn-sm" href="#:linkFechar#" data-toggle="tooltip" data-placement="top" role="button" id="btn_visualizar" title="Fechar caixa">'
                                    +'<span class="glyphicon glyphicon-saved"></span>'
                                +'</a>'
                }
            ]
      //       detailInit: function(e) {
		    //     e.detailRow.find(".itens").kendoGrid({
		    //         dataSource: e.data.itens,
		    //         columns: [
		    //             { field: "id", title:"ID", width: "80px"},
		    //             { field: "dateOpen", title:"Data De Abertura"},
		    //             { field: "dateClose", title:"Data De Fechamento" },
		    //             { field: "user", title:"Funcionário" },
		    //             { 
		    //                 field: "acoes", 
		    //                 title:"Ações" ,
		    //                 template : '<a class="btn btn-primary pull-left btn_visualizar btn-sm" href="#:linkvisualizar#" data-toggle="tooltip" data-placement="top" role="button" id="btn_visualizar" title="Visualizar">'
		    //                                 +'<span class="glyphicons glyphicons-eye-open"></span>'
		    //                             +'</a>'
		    //                             +'<a class="btn btn-primary pull-left btn_fechar btn-sm" href="#:linkvisualizar#" data-toggle="tooltip" data-placement="top" role="button" id="btn_visualizar" title="Fechar caixa">'
		    //                                 +'<span class="glyphicon glyphicon-saved"></span>'
		    //                             +'</a>'
		    //             }
		    //         ]
		    //     });
		    // }
        });
    }

});


var chart = $("#grid").data("kendoGrid");
	var dataSource = new kendo.data.DataSource( {
	  data: [{
	  		'id':10,
	  		'data':'teste'
	  }]
	});
	chart.setDataSource(dataSource);
})
</script>