       <?php
            $thead = '  <tr>
                            <th width="30">Código</th>
                            <th width="300">Produto</th>
                            <th width="160">Quantidade</th>
                            <th width="80">Ações</th>
                        </tr>';
            $tfoot = '  <tr>
                            <td>Código</td>
                            <th>Produto</th>
                            <th>Quantidade</th>
                            <td>Ações</td>
                        </tr>';  

            $tbody = '';

            foreach ($produtosrequisitados->getProdutosRequisitados() as $produto):
            $disabledButtons = ($produto->getStatus() == statusRequisicoes::APROVADO || $produto->getStatus() == statusRequisicoes::REPROVADO || $produto->getStatus() == statusRequisicoes::CANCELADO) ? 'disabled="disabled"' : '';

            $tbody .='  <tr id="'.$produto->getId().'">
                            <td>'.$produto->getId().'</td>
                            <td>'.$produto->getProdutos()->getNome().'</td>
                            <td>'.$dataFormat->formatar($produto->getQuantidade(),'decimal').' '.$produto->getProdutos()->getUnidadeMedidaEstoque()[0]->getUnidadeMedida()->getNome().'</td>
                            <td>'
                                .$this->templateFactory->getButton('reprovar', array('href'=>URL.'suprimentos/requisicoes/gerenciar/reprovarcotacaoproduto/'.$produto->getId(), 'title'=>'Reprovar', 'moreContent'=>$disabledButtons)).
                                $this->templateFactory->getButton('aprovar',array('href'=>URL.'suprimentos/requisicoes/gerenciar/aprovarcotacaoproduto/'.$produto->getId(), 'title'=>'Aprovar', 'moreContent'=>$disabledButtons.' idProdutoRequisitado="'.$produto->getId().'"')).
                            '</td>
                        </tr>';
                endforeach;
                echo $this->templateFactory->getTable('tabela', array('thead'=>$thead, 'tfoot'=>$tfoot, 'tbody'=>$tbody, 'moreContent' => 'tableProdutosRequisitado'));
            ?>
<script type="text/javascript">
    $(function(){
        //DATATABLE
        var table = $('.dataTable[tableProdutosRequisitado]').DataTable({
            order: [0,'asc']
        });
        $('.dataTable[tableProdutosRequisitado]').show()
        //EXCLUIR
        table.$('.btn_aprovar, .btn_reprovar').on('click',function(){
            var idProdutoRequisitado = $(this).attr('idProdutoRequisitado')
            $.post($(this).attr('href'),{},function(data){
                if(data == true){
                    messageDialog('Produto aprovado','success',false,null);
                    $('.btn_aprovar[idProdutoRequisitado='+idProdutoRequisitado+']').attr('disabled', 'disabled');
                    $('.btn_reprovar[idProdutoRequisitado='+idProdutoRequisitado+']').attr('disabled', 'disabled');
                }else
                {
                    messageDialog(data,'warning',false,null);
                }
            });
            return false;
        });


    })
</script>

