<div class="container">
    <div class="page-header">
      <h1>Gestão de Estoque</h1>
    </div>
    <div class="middle-content">
        <div class="row">
			<div class="col-sm-6 col-md-4">
			    <a href="<?=URL?>estoque/prateleira" class="thumbnail">
			      	<img src="<?=URL?>skin/img/imagens/prateleira.jpg" alt="..." style="height: 200px">
			      	<div class="caption text-center">
			        	<h3>PRATELEIRA</h3>
			      	</div>
			    </a>
			</div>
			<div class="col-sm-6 col-md-4">
			    <a href="<?=URL?>estoque/armazem" class="thumbnail">
			      	<img src="<?=URL?>skin/img/imagens/armazem.jpg" alt="..." style="height: 200px">
			      	<div class="caption text-center">
			        	<h3>ARMAZÉM</h3>
			      	</div>
			    </a>
			</div>
			<div class="col-sm-6 col-md-4">
			    <a href="<?=URL?>estoque/descartados" class="thumbnail">
			      	<img src="<?=URL?>skin/img/imagens/descartados.jpg" alt="..." style="height: 200px">
			      	<div class="caption text-center">
			        	<h3>DESCARTADOS</h3>
			      	</div>
			    </a>
			</div>
		</div>
    </div>
</div>


