<div class="container">
	
	<div id="fullscreen" class="fullscreenCheckout hide">
		
		<section id="telaAbrirCaixa" class="hide">
			<div class="containercheckoutAbrirCaixa">
				<figure class="center-block figureLogo thumbnail">
		      		<img src="<?=URL?>skin/img/imagens/logosupermercado.png" alt="">
				</figure>
				<div class="containerHora">
					<output id="hora" class="hora"></output>				
				</div>	
				<div class="containerData">
					<output id="data" class="data"></output>
				</div>
				<form class="form" action="<?=URL?>caixa/checkout/gerenciar/abrircaixa" id="form_abrirCaixa">
					<div class="form-group">
					    <label>Saldo Inicial em caixa</label>
					    <input type="text" class="form-control" placeholder="Saldo" name="saldoinicial">
					</div>
					<button type="submit" class="btn btn-primary pull-right">Abrir caixa</button>
				</form>
			</div>
		</section>

		<section id="telaFecharCaixa" class="hide">
			<div class="containercheckoutAbrirCaixa">
				<figure class="center-block figureLogo thumbnail">
		      		<img src="<?=URL?>skin/img/imagens/logosupermercado.png" alt="">
				</figure>
				<div class="containerHora">
					<output id="hora" class="hora"></output>				
				</div>	
				<div class="containerData">
					<output id="data" class="data"></output>
				</div>
				<form class="form" action="<?=URL?>caixa/checkout/gerenciar/fecharcaixa" id="form_fecharCaixa">
					<div class="form-group">
					    <label>Saldo Final em caixa</label>
					    <input type="text" class="form-control" placeholder="Saldo" name="saldofinal">
					</div>
					<button type="submit" class="btn btn-primary pull-right">Fechar caixa</button>
				</form>
			</div>
		</section>




		<section class="container-fluid hide" id="telaVenda">
		    <div class="row telaVenda">
		        <div class="col-sm-3 col-md-2 sidebarcheckout">
		          	<figure class="center-block figureLogo thumbnail">
			      		<img src="<?=URL?>skin/img/imagens/logosupermercado.png" alt="">
					</figure>
					<div class="containerHora">
						<output id="hora" class="hora"></output>
					</div>	
					<div class="containerData">
						<output id="data" class="data"></output>
					</div>
		          	<ul class="nav nav-sidebar">
		            	<li><a href="javascript:void(0)" class="openfullscreen">Tela cheia</a></li>
		            	<li><a href="javascript:void(0)" class="btnfecharcaixa">Fechar Caixa</a></li>
		          	</ul>
		          	<div class="row">
					  	<div class="col-xs-12 col-md-12">
					  		<?php
                          $fotoFunc = ($usuario->getFuncionario()->getFoto() != '') ? URL.'skin/uploads/funcionarios/p/'.$usuario->getFuncionario()->getFoto() : URL.'skin/img/imagens/perfil-icone.png';
                          ?>
	                        <div class="thumbnail">
					      		<img src="<?=$fotoFunc?>" alt="..." class="img-circle" style="width: 100px; margin:auto; display: table;">
					      		<div class="caption text-center">
					      			<p><?=$usuario->getFuncionario()->getNome().' '.$usuario->getFuncionario()->getSobrenome()?></p>
					      		</div>
						  	</div>
					  	</div>
					</div>
		        </div>
		        <div class="col-sm-4 col-sm-offset-2 col-md-4 col-md-offset-2 bg-primary containerProdutos">
		          	<h1 class="page-header">
		          		PRODUTOS
			      		<label class="pull-right checkoutListAutomatic">
				       		<small>Listagem automática</small>
				       		<input type="checkbox" name="automaticList" checked="checked">
				      	</label>
		          	</h1>
					<div class="row">
						<div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">


							<div>
								<!-- Nav tabs -->
								<ul class="nav nav-tabs" role="tablist">
								    <li role="presentation" class="active"><a href="#porcodigo" aria-controls="porcodigo" role="tab" data-toggle="tab">Por código de barras</a></li>
								    <li role="presentation"><a href="#pordescricao" aria-controls="pordescricao" role="tab" data-toggle="tab">Por descrição</a></li>
								</ul>

								<!-- Tab panes -->
								<div class="tab-content">
								    <div role="tabpanel" class="tab-pane active" id="porcodigo">
										<div class="form-group col-xs-12 col-md-12 col-sm-12 col-lg-12">
						                    <label>Código de barras</label>
						                    <input type="text" class="form-control" name="codigobarras" maxlength="13" placeholder="Código de barras">
						                </div>
								    </div>
								    <div role="tabpanel" class="tab-pane" id="pordescricao">
								    	<div class="form-group col-xs-12 col-md-12 col-sm-12 col-lg-12">
						                    <label>Produtos</label>
						                    <select name="listaproduto" class="form-control">
						                    	<option value="" selected="selected">Selecione</option>
						                        <?php if(!empty($produtos)):?>
						                        <?php foreach ($produtos as $produtoestoque):?>
						                        <option value="<?=$produtoestoque->getProduto()->getId()?>"><?=$produtoestoque->getProduto()->getNome()?></option>
						                        <?php endforeach;?>
						                        <?php endif;?>
						                    </select>
						                </div>

								    </div>
								</div>
								
							</div>


							<section class="containerProdutoUnitario hide">
								<input type="hidden" name="id_produto" value="">
								<div class="listProducts">
									<div class="item">
										<h3 id="nomeProduto"></h3>
										<div class="col-xs-12 col-md-12">
										    <div class="thumbnail">
										      	<img src="" alt="" id="fotoProduto" style="width: 200px;">
										    </div>
										</div>
									</div>
								</div>
								<div class="subtotal">
									<div class="form-group">
									    <label class="col-sm-4 control-label">QUANTIDADE</label>
									    <div class="col-sm-4">
									      	<input type="text" class="form-control" value="1" min="1" name="quantidade" id="quantidade" readonly="readonly">
									    </div>
									    <div class="col-sm-4">
									    	<label id="unidadeMed">kg</label>
									    </div>
									</div>
									<div class="form-group">
									    <h3 class="col-sm-7 control-label">VALOR UNITÁRIO</h3>
									    <div class="col-sm-5">
									      	<h3 id="valorUnitario"></h3>
									      	<input type="hidden" value="1" name="valorUnitario" class="form-control">
									    </div>
									</div>
									<div class="form-group">
									    <h3 class="col-sm-5 control-label">SUBTOTAL</h3>
									    <div class="col-sm-7">
									      	<h2 id="subtotalProduto" class="text-right"></h2>
									    </div>
									</div>

									<div class="btn-group pull-right">
									  	<button type="button" class="btn btn-success btnListar hide">Listar</button>
									</div>
								</div>
							</section>
							<a href="#" id="produtoUnitario"></a>
						</div>
					</div>
		        </div>




				<div class="col-sm-4 col-sm-offset-2 col-md-4 col-md-offset-2 bg-primary hide containerPagarCompra">
					<h1 class="page-header">PAGAMENTO</h1>
					<div class="row">
						<div class="col-sm-6 col-md-4">
						    <a href="javascript:void(0)" class="thumbnail btnformaPagamento" type="DINHEIRO">
						    	<figure class="text-center">
						    		<span class="glyphicons glyphicons-money"></span>
						    	</figure>
						      	
						      	<div class="caption">
						        	<h5 class="text-center">DINHEIRO</h5>
						      	</div>
						    </a>
						</div>

						<div class="col-sm-6 col-md-4">
						    <a href="javascript:void(0)" class="thumbnail btnformaPagamento" type="CARTAODEBITO">
						    	<figure  class="text-center">
						    		<span class="glyphicons glyphicons-credit-card"></span>
						    	</figure>
						      	
						      	<div class="caption">
						        	<h5 class="text-center">CARTÃO DE DÉBITO</h5>
						      	</div>
						    </a>
						</div>

						<div class="col-sm-6 col-md-4">
						    <a href="javascript:void(0)" class="thumbnail btnformaPagamento" type="CARTAOCREDITO">
						    	<figure class="text-center">
						    		<span class="glyphicons glyphicons-credit-card"></span>
						    	</figure>
						      	
						      	<div class="caption">
						        	<h5 class="text-center">CARTÃO DE CRÉDITO</h5>
						      	</div>
						    </a>
						</div>
					</div>
				</div>


				<div class="col-sm-4 col-sm-offset-2 col-md-4 col-md-offset-2 bg-primary hide containerFinalizarCompra">
					<h2 class="page-header">FINALIZANDO PAGAMENTO</h2>
					<div class="row">
						<div class="form-group">
						    <h3 class="col-sm-5 control-label">SUBTOTAL</h3>
						    <div class="col-sm-7">
						      	<h2 id="subtotalProduto" class="text-right"></h2>
						      	<input type="hidden" name="subtotal" value="">
						    </div>
						</div>
						<div class="col-sm-12 col-md-12 hide" id="tipo_DINHEIRO">
							<div class="wel">
							    <h3><small>PAGAMENTO ESCOLHIDO: </small> DINHEIRO</h3>
							    
							    <div class="form-group">
								    <label>Valor pago</label>
								    <input type="text" class="form-control" placeholder="Digite o valor recebido" name="valorrecebido">
								</div>

								<div class="form-group">
								    <label>Troco</label>
								    <h1 id="troco"></h1>
								</div>
							</div>
						</div>

						<div class="col-sm-12 col-md-12 hide" id="tipo_CARTAODEBITO">
							<div class="wel">
							    <h3><small>PAGAMENTO ESCOLHIDO: </small> CARTÃO DE DÉBITO</h3>
								<div class="form-group">
								    <label>Status da operação</label>
								    <p class="form-control">Aguardando cartão</p>
								</div>
							</div>
						</div>

						<div class="col-sm-12 col-md-12 hide" id="tipo_CARTAOCREDITO">
							<div class="wel">
							    <h3><small>PAGAMENTO ESCOLHIDO: </small> CARTÃO DE CRÉDITO</h3>
							    <div class="form-group">
								    <label>Status da operação</label>
								    <p class="form-control">Aguardando cartão</p>
								</div>
							</div>
						</div>

						<div class="btn-group pull-right">
							<button type="button" class="btn btn-success btnFinalizar">Finalizar</button>
						</div>
					</div>
				</div>







		        <div class="col-sm-4 col-sm-offset-2 col-md-6 col-md-offset-6 containerListaCompra">
		          	<h1 class="page-header">LISTA DA COMPRA</h1>
					<div class="row">
					  	<div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">
					  		<table class="table table-striped" cellspacing="0" id="listcarrinho">
							    <thead>
							        <tr>
							        	<th>#</th>
							        	<th width="360">Item</th>
							        	<th>QTDE.</th>
							        	<th>R$ (Unid.)</th>
							        </tr>
							    </thead>
							</table>
							<div class="containerlistaCarrinho">
							  	<table class="table table-striped" cellspacing="0" id="listcarrinho">
								    <tbody>
								    	
								    </tbody>
								</table>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="well">TOTAL A PAGAR <small>R$</small> <span id="subtotal"></span></div>
						<div class="btn-group btn-lg">
							<!-- <button class="cancelarcompra btn btn-danger">CANCELAR COMPRA <span class="glyphicon glyphicon-remove-circle"></span></button> -->
							<button class="pagarcompra btn btn-primary " disabled="disabled">PAGAR COMPRA <span class="glyphicons glyphicons-usd"></span></button>
						</div>
					</div>
		        </div>


				

		    </div>
	    </section>


	</div>

	<div id="telaPrincipal" class="">
		<div class="containercheckoutInicio">
			<figure class="center-block figureLogo thumbnail">
	      		<img src="<?=URL?>skin/img/imagens/logosupermercado.png" alt="">
			</figure>
			<div class="containerHora">
				<output id="hora"></output>
			</div>	
			<div class="containerData">
				<output id="data"></output>
			</div>
			<a href="javascript:void(0)" class="openfullscreen">Clique para iniciar <span class="glyphicons glyphicons-hand-up"></span></a>
			<!-- <a href="#" class="exitfullscreen" style="display: none">Click to exit fullscreen</a> -->
		</div>
	</div>


</div>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskMoney.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/fullscreen/jquery.fullscreen.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/caixas/checkout/checkout.js"></script>