<div class="container">
    <?php
        $btnVoltar = $this->templateFactory->getButton('voltar',array('href'=>URL.''));
        echo $this->templateFactory->getButton('actions_buttons',array('buttons'=>$btnVoltar));
    ?>
    <div class="page-header">
      <h1>Minha Empresa</h1>
    </div>
    <form action="<?=URL?>configuracoes/empresa/gerenciar/atualizar" method="post" id="form_fornecedores">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Empresariais</div>
            <div class="panel-body">
                <div class="col-xs-6 col-md-3 col-sm-3 col-lg-3">
                    <div class="col-xs-6 col-md-3">
                        <label for="foto" class=" inputFoto preview-lg">
                            <div class="thumbnail img-preview preview-lg">
                                <img src="<?=URL?>skin/img/imagens/semlogo.jpg" id="img_previous">
                            </div>
                            <input type="file" name="foto" id="foto" accept="image/*">
                        </label>
                    </div>
                </div>
                <div class="col-xs-6 col-md-3 col-sm-3 col-lg-9">
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                        <label>Razão Social</label>
                        <input type="text" class="form-control" placeholder="Razão Social" aria-describedby="basic-addon1" name="razao_social">
                    </div>


                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                        <label>Nome Fantasia</label>
                        <input type="text" class="form-control" placeholder="Nome Fantasia" aria-describedby="basic-addon1" name="nome_fantasia">
                    </div>

                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                        <label>CNPJ</label>
                        <input type="text" class="form-control" placeholder="CNPJ" aria-describedby="basic-addon1" name="cnpj">
                    </div>

                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                        <label>Proprietário</label>
                        <input type="text" class="form-control" placeholder="Proprietário" aria-describedby="basic-addon1" name="proprietario">
                    </div>

                    
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-12">
                        <label>Site</label>
                        <input type="text" class="form-control" placeholder="Site" name="site">
                    </div>
                     <div class="btn-group pull-right" role="group">
                             <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</button>
                     </div>

                   
                </div>
            </div>
        </div>
        
    </div>
</div>       

<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<link href="<?=URL?>skin/js/croper/cropper.min.css" rel="stylesheet">
<link href="<?=URL?>skin/js/croper/main.css" rel="stylesheet">
<script src="<?=URL?>skin/js/croper/cropper.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.validate.js"></script>
<script type="text/javascript">
    
 $(function(){
    /*MASCARAS DE CAMPOS*/
    $('input[name=data_visita]').datepicker({ dateFormat: 'dd/mm/yy',changeMonth: true, changeYear: true,yearRange: "-100:+0" });
    $('input[name=retorno]').wvmask('numero')
    $('input[name=cep]').wvmask('cep')
    $('input[name=numero]').wvmask('numero')
    $('input[name=cnpj]').mask('99.999.999/9999-99');
    $('#form_fornecedores').validaCep();


    //UPLOAD DA IMAGEM
    $('#form_fornecedores').uploadImage();
 $('#form_fornecedores').submit(function(){
$('#form_fornecedores').uploadForm({
            'parameters': parameters,
            'reload':true
        });
        return false;
    });
        
    

    })
</script>

