<div class="container">
    <?php
    $dataFormat = new dataformat();
       $btnVoltar = $this->templateFactory->getButton(
											       		"voltar",
											       		array( 'href'=>URL.'produtos/gerenciar/precos/'.$preco->getProduto()->getId() )
											       	);
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnVoltar));    ?>
    <div class="page-header">
      <h1>Tabela de preços<small> editar</small></h1>
    </div>
    <form action="<?=URL?>produtos/gerenciar/atualizarPreco" method="post" id="formPreco">
        <div class="panel panel-default">
            <div class="panel-heading">Valores</div>
            <div class="panel-body">

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-9">
                    <label>Preço</label>
                    <input type="text" class="form-control" placeholder="Preço" name="preco" value="<?=$dataFormat->formatar($preco->getPreco(), 'decimal')?>">
                </div>
	
                <div class="checkbox checkbox-primary col-xs-6 col-md-3 col-sm-3 col-lg-3">
				    <input type="checkbox" id="checkbox1" name="padrao" <?=($preco->getPadrao() ==true) ? 'checked="checked"' : ''?>>
				    <label for="checkbox1">
				        Tornar padrão
				    </label>
				</div>
               
            </div>
        </div>

        <div class="panel panel-default painelPeriodo <?=($preco->getPadrao() ==true) ? 'hide' : ''?>">
            <div class="panel-heading">Período</div>
            <div class="panel-body">
                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-12">
                    
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                    	<label>De: </label>
                        <input type="text" class="form-control" placeholder="De quando" name="de" value="<?=$preco->getDataInicio()?>">
                    </div>

                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                    	<label>Até: </label>
                        <input type="text" class="form-control" placeholder="Até quando" name="ate" value="<?=$preco->getDataFim()?>">
                    </div>
                </div>
            </div>
        </div>
		<input type="hidden" name="idProduto" value="<?=$idProduto?>">
		<div class="btn-group pull-right" role="group">
            <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</button>
        </div>

    </form>
</div>

<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskMoney.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>

<script>
$(function(){
	
	$("input[name=preco]").maskMoney({symbol:'R$ ', decimal:",", thousands:""});
	$('input[name=padrao]').change(function(event) {
		$('.painelPeriodo').toggleClass('hide')
		$('input[name=de],input[name=ate]').val('')
	});
    $( "input[name=de]" ).datepicker({
        defaultDate: "+1w",
        dateFormat: 'dd/mm/yy',
        changeMonth: true, 
        changeYear: true,
        yearRange: "-0:+1",
        numberOfMonths: 2,
        minDate:0,
        onClose: function( selectedDate ) {
            $( "input[name=ate]" ).datepicker( "option", "minDate", selectedDate );
        }
    });
    $( "input[name=ate]" ).datepicker({
        defaultDate: "+1w",
        dateFormat: 'dd/mm/yy',
        changeMonth: true, 
        changeYear: true,
        yearRange: "-0:+1", 
        numberOfMonths: 2,
        onClose: function( selectedDate ) {
            $( "input[name=de]" ).datepicker( "option", "maxDate", selectedDate );
        }
    });


    $('#formPreco').submit(function(event) {
    	
    	$('#formPreco').uploadForm({
            'reload':true
        });
    	return false;
    });
})
</script>