<div class="container">
    <?php
    	$btnVoltar = $this->templateFactory->getButton(
											       		"voltar",
											       		array( 'href'=>URL.'produtos/gerenciar/' )
											       	);
        $btnCadastrar = $this->templateFactory->getButton("cadastrar", array('href'=>URL.'produtos/gerenciar/cadastrarprecos/'.$idProduto), URL.'produtos/gerenciar/cadastrarprecos');
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnCadastrar.$btnVoltar));
    ?>
    <div class="page-header">
      <h1>Tabela de preços <small><?=$produtoPreco->getNome()?></small></h1>
    </div>
    <div class="middle-content">
        <img src="<?=URL?>img/loading3.gif" style="display: block;  margin: auto; width: 200px;" id="loadTable">
        <table class="dataTable rwd-table" cellspacing="0" width="100%" style="display:none">
            <thead>
                <tr>
                    <th width="100">#</th>
                    <th width="160">Preço</th>
                    <th width="160">Período</th>
                    <th width="180">Ações</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>#</th>
                    <th>Preço</th>
                    <th>Período</th>
                    <th>Ações</th>
                </tr>
            </tfoot>
            <tbody>

            <?php if(!empty($produtoPreco)):?>
            <?php foreach ($produtoPreco->getPrecos() as $preco): ?>
                <tr id="<?=$preco->getId()?>">
                    <td><?=$preco->getId()?> <?= ($preco->getPadrao())? '<span class="glyphicon glyphicon-ok"></span>' : ''?></td>
                    <td><?=$dataFormat->formatar($preco->getPreco(), 'moeda')?></td>
                    <td>De: <?=$dataFormat->formatar($preco->getDataInicio(),'data')?> Até: <?=$dataFormat->formatar($preco->getDataFim(),'data')?></td>
                    <td>
                        <a class="btn btn-primary btn_editar btn-sm" href="<?=URL?>produtos/marcas/gerenciar/editar/<?=$preco->getId()?>" role="button" id-record="<?=$preco->getId()?>" ><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                        <a class="btn btn-danger btn_excluir btn-sm" href="javascript:void(0)" role="button" id="<?=$preco->getId()?>" data-value="<?=status::EXCLUIDO?>" ><span class="glyphicon glyphicon-remove"></span>Excluir</a>
                    </td>
                </tr>
            <?php
                endforeach;
            endif;
            ?>
                
            </tbody>
        </table>
    </div>

</div>

<script type="text/javascript">
    $(function(){
        //DATATABLE
        // var table = $('.dataTable').DataTable({
        //     order: [0,'asc']
        // });

        //EXCLUIR
        $('.btn_excluir').on('click',function(){
            var id = $(this).attr('id');
            var status = $(this).data('value');
            var modalDelete = $('#modalDelete').modal('show')
            $('.btn_ok','#modalDelete').on('click', function(event) {
                $.post(url+'produtos/marcas/gerenciar/excluir',{id:id,status:status},function(data){
                    console.log(data)
                    if(data == true){
                        $('#modalDelete').modal('hide');
                        $('tr#'+id).hide();
                    }
                });
            });
        });


    })
</script>

