<div class="container">
    <?php
        $btnVoltar = $this->templateFactory->getButton('voltar',array('href'=>URL.'fornecedores/gerenciar'));
        echo $this->templateFactory->getButton('actions_buttons',array('buttons'=>$btnVoltar));
    ?>
    <div class="page-header">
      <h1>Fornecedores<small> Cadastro</small></h1>
    </div>
    <form action="<?=URL?>fornecedores/gerenciar/inserir" method="post" id="form_fornecedores">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Empresariais</div>
            <div class="panel-body">
                <div class="col-xs-6 col-md-3 col-sm-3 col-lg-3">
                    <div class="col-xs-6 col-md-3">
                        <label for="foto" class=" inputFoto preview-lg">
                            <div class="thumbnail img-preview preview-lg">
                                <img src="<?=URL?>skin/img/imagens/semlogo.jpg" id="img_previous">
                            </div>
                            <input type="file" name="foto" id="foto" accept="image/*">
                        </label>
                    </div>
                </div>
				<div class="col-xs-6 col-md-3 col-sm-3 col-lg-9">
	                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
	                    <label>Razão Social</label>
	                    <input type="text" class="form-control" placeholder="Razão Social" aria-describedby="basic-addon1" name="razao_social">
	                </div>


	                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
	                    <label>Nome Fantasia</label>
	                    <input type="text" class="form-control" placeholder="Nome Fantasia" aria-describedby="basic-addon1" name="nome_fantasia">
	                </div>

	                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
	                    <label>CNPJ</label>
	                    <input type="text" class="form-control" placeholder="CNPJ" aria-describedby="basic-addon1" name="cnpj">
	                </div>

	                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
	                    <label>CPF</label>
	                    <input type="text" class="form-control" placeholder="CPF" aria-describedby="basic-addon1" name="cpf">
	                </div>
	                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
	                    <label>Pessoa</label>
	                    <select class="form-control" name="pessoa">
	                        <option value="" selected="selected" disabled="disabled">..Selecione..</option>
	                        <option value="PF">Física</option>
	                        <option value="PJ">Jurídica</option>
	                    </select>
	                </div>
	                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
	                    <label>Site</label>
	                    <input type="text" class="form-control" placeholder="Site" aria-describedby="basic-addon1" name="site">
	                </div>

	                <div class="form-group col-xs-6 col-md-12 col-sm-12 col-lg-12">
	                    <label>Observações</label>
	                    <textarea class="form-control" placeholder="Observações" name="observacoes"></textarea>
	                </div>
	            </div>
            </div>
        </div>
        
        <div class="panel panel-default">
            <div class="panel-heading">Contatos</div>
            <div class="panel-body">
                <div class="form-group group_tel">
                	<div class="form-group col-xs-6 col-md-12 col-sm-12 col-lg-12">
	                    <label>Nome para contato</label>
	                    <input type="text" name="nomeContato" placeholder="Nome para contato" class="form-control" />
	                </div>
                    <div class="form-group col-xs-12 col-md-6 col-sm-6 col-lg-6">
                        <label>E-mail</label>
                        <input type="email" name="email" placeholder="E-mail" class="form-control" />
                    </div>
                    <div class="form-group col-xs-12 col-md-6 col-sm-6 col-lg-6">
                        <label>Telefone</label>
                        <input type="tel" name="telefone" placeholder="Telefone" class="form-control" />
                    </div>
                </div>
            </div>
        </div>



       <div class="panel panel-default">
            <div class="panel-heading">Endereço</div>
            <div class="panel-body">

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>CEP</label>
                    <input type="text" class="form-control" placeholder="CEP" name="cep" id="cep">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                    <label>Logradouro</label>
                    <input type="text" class="form-control" placeholder="Lougradouro" name="logradouro" id="rua">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>Número</label>
                    <input type="text" class="form-control" placeholder="Número" name="numero" id="numero">
                </div>
                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>Complemento</label>
                    <input type="text" class="form-control" placeholder="Complemento" name="complemento" id="complemento">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-5">
                    <label>Bairro</label>
                    <input type="text" class="form-control" placeholder="Bairro" name="bairro" id="bairro">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-5">
                    <label>Cidade</label>
                    <input type="text" class="form-control" placeholder="Cidade" name="cidade" id="cidade">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>UF</label>
                    <select class="form-control" name="estado" id="uf">
                        <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                        <option value="AC">AC - Acre</option>
                        <option value="AL">AL - Alagoas</option>
                        <option value="AP">AP - Amapá</option>
                        <option value="AM">AM - Amazonas</option>
                        <option value="BA">BA - Bahia</option>
                        <option value="CE">CE - Ceará</option>
                        <option value="DF">DF - Distrito Federal</option>
                        <option value="GO">GO - Goiás</option>
                        <option value="ES">ES - Espírito Santo</option>
                        <option value="MA">MA - Maranhão</option>
                        <option value="MT">MT - Mato Grosso</option>
                        <option value="MS">MS - Mato Grosso do Sul</option>
                        <option value="MG">MG - Minas Gerais</option>
                        <option value="PA">PA - Pará</option>
                        <option value="PB">PB - Paraiba</option>
                        <option value="PR">PR - Paraná</option>
                        <option value="PE">PE - Pernambuco</option>
                        <option value="PI">PI - Piauí­</option>
                        <option value="RJ">RJ - Rio de Janeiro</option>
                        <option value="RN">RN - Rio Grande do Norte</option>
                        <option value="RS">RS - Rio Grande do Sul</option>
                        <option value="RO">RO - Rondônia</option>
                        <option value="RR">RR - Roraima</option>
                        <option value="SP">SP - São Paulo</option>
                        <option value="SC">SC - Santa Catarina</option>
                        <option value="SE">SE - Sergipe</option>
                        <option value="TO">TO - Tocantins</option>
                    </select>
                </div>
                
            </div>
        </div><!-- fim panel endereco -->
        <div class="btn-group pull-right" role="group">
            <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</button>
        </div>
    </form>
</div>

<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<link href="<?=URL?>skin/js/croper/cropper.min.css" rel="stylesheet">
<link href="<?=URL?>skin/js/croper/main.css" rel="stylesheet">
<script src="<?=URL?>skin/js/croper/cropper.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskMoney.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/fornecedores/cadastrar.js"></script>