<div class="container">
    <?php
        $btnVoltar = $this->templateFactory->getButton('voltar',array('href'=>URL.'fornecedores/gerenciar'));
        echo $this->templateFactory->getButton('actions_buttons',array('buttons'=>$btnVoltar));
    ?>
    <div class="page-header">
      <h1>Fornecedores<small> Edição</small></h1>
    </div>
    <form action="<?=URL?>fornecedores/gerenciar/atualizar" method="post" id="form_fornecedores">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Empresariais</div>
            <div class="panel-body">
                <div class="col-xs-6 col-md-3 col-sm-3 col-lg-3">
                    <div class="col-xs-6 col-md-3">
                        <label for="foto" class="inputFoto preview-lg">
                            <div class="thumbnail img-preview preview-lg">
                            <?php
                            $foto = $fornecedor->getFoto() != '' ? URL.'skin/uploads/fornecedores/p/'.$fornecedor->getFoto(): URL.'skin/img/imagens/semfoto.jpg';
                            ?>
                                <img src="<?=$foto?>" id="img_previous">
                            </div>
                            <input type="hidden" name="nome_foto" value="<?=$fornecedor->getFoto()?>">
                            <input type="file" name="foto" id="foto" accept="image/*">
                        </label>
                    </div>
                </div>
				<div class="col-xs-6 col-md-3 col-sm-3 col-lg-9">
	                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
	                    <label>Razão Social</label>
	                    <input type="text" class="form-control" placeholder="Razão Social" aria-describedby="basic-addon1" name="razao_social" value="<?=$fornecedor->getRazaoSocial()?>">
	                </div>


	                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
	                    <label>Nome Fantasia</label>
	                    <input type="text" class="form-control" placeholder="Nome Fantasia" aria-describedby="basic-addon1" name="nome_fantasia" value="<?=$fornecedor->getNomeFantasia()?>">
	                </div>

	                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
	                    <label>CNPJ</label>
	                    <input type="text" class="form-control" placeholder="CNPJ" aria-describedby="basic-addon1" name="cnpj" value="<?=$fornecedor->getCnpj()?>">
	                </div>

	                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
	                    <label>CPF</label>
	                    <input type="text" class="form-control" placeholder="CPF" aria-describedby="basic-addon1" name="cpf" value="<?=$fornecedor->getCpf()?>">
	                </div>
	                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
	                    <label>Pessoa</label>
	                    <select class="form-control" name="pessoa">
	                        <option value="" selected="selected" disabled="disabled">..Selecione..</option>
	                        <option value="PF" <?=$fornecedor->getPessoa() == "PF" ? 'selected="selected"' : ''?>>Física</option>
	                        <option value="PJ" <?=$fornecedor->getPessoa() == "PJ" ? 'selected="selected"' : ''?>>Jurídica</option>
	                    </select>
	                </div>
	                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
	                    <label>Site</label>
	                    <input type="text" class="form-control" placeholder="Site" aria-describedby="basic-addon1" name="site" value="<?=$fornecedor->getSite()?>"> 
	                </div>

	                <div class="form-group col-xs-6 col-md-12 col-sm-12 col-lg-12">
	                    <label>Observações</label>
	                    <textarea class="form-control" placeholder="Observações" name="observacoes"><?=$fornecedor->getObservacoes()?></textarea>
	                </div>
	            </div>
            </div>
        </div>
        




        <div class="panel panel-default">
            <div class="panel-heading">Contatos</div>
            <div class="panel-body">
                <div class="form-group group_tel">
                	<div class="form-group col-xs-6 col-md-12 col-sm-12 col-lg-12">
	                    <label>Nome para contato</label>
	                    <input type="text" name="nomeContato" placeholder="Nome para contato" class="form-control" value="<?=$fornecedor->getNomeContato()?>"/>
	                </div>
                    <div class="form-group col-xs-12 col-md-6 col-sm-6 col-lg-6">
                        <label>E-mail</label>
                        <input type="email" name="email" placeholder="E-mail" class="form-control" value="<?=$fornecedor->getEmail()?>"/>
                    </div>
                    <div class="form-group col-xs-12 col-md-6 col-sm-6 col-lg-6">
                        <label>Telefone</label>
                        <input type="tel" name="telefone" placeholder="Telefone" class="form-control" value="<?=$fornecedor->getTelefone()?>"/>
                    </div>
                </div>
            </div>
        </div>





        
       
       <div class="panel panel-default">
            <div class="panel-heading">Endereço</div>
            <div class="panel-body">

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>CEP</label>
                    <input type="text" class="form-control" placeholder="CEP" name="cep" id="cep" value="<?=$fornecedor->getEndereco()->getCep()?>">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                    <label>Logradouro</label>
                    <input type="text" class="form-control" placeholder="Lougradouro" name="logradouro" id="rua"  value="<?=$fornecedor->getEndereco()->getLogradouro()?>">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>Número</label>
                    <input type="text" class="form-control" placeholder="Número" name="numero" id="numero"  value="<?=$fornecedor->getEndereco()->getNumero()?>">
                </div>
                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>Complemento</label>
                    <input type="text" class="form-control" placeholder="Complemento" name="complemento" id="complemento"  value="<?=$fornecedor->getEndereco()->getComplemento()?>">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-5">
                    <label>Bairro</label>
                    <input type="text" class="form-control" placeholder="Bairro" name="bairro" id="bairro"  value="<?=$fornecedor->getEndereco()->getBairro()?>">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-5">
                    <label>Cidade</label>
                    <input type="text" class="form-control" placeholder="Cidade" name="cidade" id="cidade"  value="<?=$fornecedor->getEndereco()->getCidade()?>">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>UF</label>
                    <select class="form-control" name="estado" id="uf">
                        <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                        <option value="AC" <?=$fornecedor->getEndereco()->getEstado() == 'AC' ? 'selected="selected"' : ''?>>AC - Acre</option>
                        <option value="AL" <?=$fornecedor->getEndereco()->getEstado() == 'AL' ? 'selected="selected"' : ''?>>AL - Alagoas</option>
                        <option value="AP" <?=$fornecedor->getEndereco()->getEstado() == 'AP' ? 'selected="selected"' : ''?>>AP - Amapá</option>
                        <option value="AM" <?=$fornecedor->getEndereco()->getEstado() == 'AM' ? 'selected="selected"' : ''?>>AM - Amazonas</option>
                        <option value="BA" <?=$fornecedor->getEndereco()->getEstado() == 'BA' ? 'selected="selected"' : ''?>>BA - Bahia</option>
                        <option value="CE" <?=$fornecedor->getEndereco()->getEstado() == 'CE' ? 'selected="selected"' : ''?>>CE - Ceará</option>
                        <option value="DF" <?=$fornecedor->getEndereco()->getEstado() == 'DF' ? 'selected="selected"' : ''?>>DF - Distrito Federal</option>
                        <option value="GO" <?=$fornecedor->getEndereco()->getEstado() == 'GO' ? 'selected="selected"' : ''?>>GO - Goiás</option>
                        <option value="ES" <?=$fornecedor->getEndereco()->getEstado() == 'ES' ? 'selected="selected"' : ''?>>ES - Espírito Santo</option>
                        <option value="MA" <?=$fornecedor->getEndereco()->getEstado() == 'MA' ? 'selected="selected"' : ''?>>MA - Maranhão</option>
                        <option value="MT" <?=$fornecedor->getEndereco()->getEstado() == 'MT' ? 'selected="selected"' : ''?>>MT - Mato Grosso</option>
                        <option value="MS" <?=$fornecedor->getEndereco()->getEstado() == 'MS' ? 'selected="selected"' : ''?>>MS - Mato Grosso do Sul</option>
                        <option value="MG" <?=$fornecedor->getEndereco()->getEstado() == 'MG' ? 'selected="selected"' : ''?>>MG - Minas Gerais</option>
                        <option value="PA" <?=$fornecedor->getEndereco()->getEstado() == 'PA' ? 'selected="selected"' : ''?>>PA - Pará</option>
                        <option value="PB" <?=$fornecedor->getEndereco()->getEstado() == 'PB' ? 'selected="selected"' : ''?>>PB - Paraiba</option>
                        <option value="PR" <?=$fornecedor->getEndereco()->getEstado() == 'PR' ? 'selected="selected"' : ''?>>PR - Paraná</option>
                        <option value="PE" <?=$fornecedor->getEndereco()->getEstado() == 'PE' ? 'selected="selected"' : ''?>>PE - Pernambuco</option>
                        <option value="PI" <?=$fornecedor->getEndereco()->getEstado() == 'PI' ? 'selected="selected"' : ''?>>PI - Piauí­</option>
                        <option value="RJ" <?=$fornecedor->getEndereco()->getEstado() == 'RJ' ? 'selected="selected"' : ''?>>RJ - Rio de Janeiro</option>
                        <option value="RN" <?=$fornecedor->getEndereco()->getEstado() == 'RN' ? 'selected="selected"' : ''?>>RN - Rio Grande do Norte</option>
                        <option value="RS" <?=$fornecedor->getEndereco()->getEstado() == 'RS' ? 'selected="selected"' : ''?>>RS - Rio Grande do Sul</option>
                        <option value="RO" <?=$fornecedor->getEndereco()->getEstado() == 'RO' ? 'selected="selected"' : ''?>>RO - Rondônia</option>
                        <option value="RR" <?=$fornecedor->getEndereco()->getEstado() == 'RR' ? 'selected="selected"' : ''?>>RR - Roraima</option>
                        <option value="SP" <?=$fornecedor->getEndereco()->getEstado() == 'SP' ? 'selected="selected"' : ''?>>SP - São Paulo</option>
                        <option value="SC" <?=$fornecedor->getEndereco()->getEstado() == 'SC' ? 'selected="selected"' : ''?>>SC - Santa Catarina</option>
                        <option value="SE" <?=$fornecedor->getEndereco()->getEstado() == 'SE' ? 'selected="selected"' : ''?>>SE - Sergipe</option>
                        <option value="TO" <?=$fornecedor->getEndereco()->getEstado() == 'TO' ? 'selected="selected"' : ''?>>TO - Tocantins</option>
                    </select>
                    <input type="hidden" name="id_endereco" value="<?=$fornecedor->getEndereco()->getId()?>">
                </div>
                
            </div>
        </div><!-- fim panel endereco -->
		<input type="hidden" name="id_fornecedor" value="<?=$fornecedor->getId()?>">
        <div class="btn-group pull-right" role="group">
            <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</button>
        </div>
    </form>
</div>

<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<link href="<?=URL?>skin/js/croper/cropper.min.css" rel="stylesheet">
<link href="<?=URL?>skin/js/croper/main.css" rel="stylesheet">
<script src="<?=URL?>skin/js/croper/cropper.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskMoney.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/fornecedores/editar.js"></script>