<div class="container">
    <?php
        $btnCadastrar = $this->templateFactory->getButton("cadastrar",array('href'=>URL.'fornecedores/gerenciar/cadastrar'));
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnCadastrar));
    ?>
    <div class="page-header">
      <h1>Fornecedores</h1>
    </div>
    <div class="middle-content">
        <table class="dataTable rwd-table" cellspacing="0" width="100%" {{moreContent}} style="display:none">
            <thead>
                <tr>
                    <th width="20">ID</th>
                    <th width="40">Foto</th>
                    <th width="100">Razão social</th>
                    <th width="160">Nome Fantasia</th>
                    <th width="160">CPF</th>
                    <th width="120">CNPJ</th>
                    <th width="100">Status (Ativo/Inativo)</th>
                    <th width="180">Ações</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>ID</th>
                    <th>Foto</th>
                    <th>Razão social</th>
                    <th>Nome Fantasia</th>
                    <th>CPF</th>
                    <th>CNPJ</th>
                    <th>Status (Ativo/Inativo)</th>
                    <th>Ações</th>
                </tr>
            </tfoot>
            <tbody>
            <?php
            if(!empty($fornecedores)):
                $tbody = '';
                foreach ($fornecedores as $fornec):
                    $foto = $fornec->getFoto() != '' ? URL.'skin/uploads/fornecedores/p/'.$fornec->getFoto() : URL.'skin/img/imagens/semlogo.jpg';
                    $ativo = ($fornec->getStatus() == status::ATIVO) ? 'selected="selected"' : '';
                    $inativo = ($fornec->getStatus() == status::INATIVO) ? 'selected="selected"' : '';
            ?>
                <tr id="<?=$fornec->getId()?>">
                    <td><?=$fornec->getId()?></td>
                    <td><img src="<?=$foto?>" style=" width: 60px; height: 60px;" class="img-circle"></td>
                    <td><?=$fornec->getRazaoSocial()?></td>
                    <td><?=$fornec->getNomeFantasia()?></td>
                    <td><?=$fornec->getCpf()?></td>
                    <td><?=$fornec->getCnpj()?></td>
                    <td>
                        <select name="status" id="<?=$fornec->getId()?>" class="statusSelect">
                            <option value="<?=status::ATIVO?>" class="active" <?=$ativo?>>Ativo</option>
                            <option value="<?=status::INATIVO?>" class="inactive" <?=$inativo?>>Inativo</option>
                        </select>
                    </td>
                    <td>
                        <?=$this->templateFactory->getButton('editar',array('href'=> URL.'fornecedores/gerenciar/editar/'.$fornec->getId()), URL.'fornecedores/gerenciar/editar/')?>
                        <?=$this->templateFactory->getButton('excluir', array('id'=> $fornec->getId()), URL.'fornecedores/gerenciar/excluir/')?>

                    '</td>
                </tr>
                <?php
                endforeach;
            endif;
            ?>
            </tbody>
        </table>


        
                
            </tbody>
        </table>
    </div>

</div>
<script type="text/javascript" src="<?=URL?>skin/js/fornecedores/fornecedores.js"></script>
