<div class="container">
    <?php
        $btnVoltar = $this->templateFactory->getButton("voltar",array('href'=>URL.'funcionarios/cargos'));
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnVoltar));
    ?>
    <div class="page-header">
      <h1>Cargos<small> Editar</small></h1>
    </div>
    <form action="<?=URL?>funcionarios/cargos/gerenciar/atualizar" method="post" id="form_cargo">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Gerais</div>
            <div class="panel-body">

                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Setor</span>
                    <input type="text" class="form-control" placeholder="Setor" name="setor" value="<?=$cargo->getSetor()?>">
                </div>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Nome</span>
                    <input type="text" class="form-control" placeholder="Nome" name="nome" value="<?=$cargo->getNome()?>">
                </div>
                <input type="hidden" name="idCargo" value="<?=$cargo->getId()?>">
                <div class="btn-group pull-right" role="group">
                    <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</button>
                </div>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/funcionarios/cargos/editar.js"></script>