<div class="container">
    <?php
        $btnCadastrar = $this->templateFactory->getButton("cadastrar",array('href'=>URL.'funcionarios/cargos/gerenciar/cadastrar'));
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnCadastrar));
    ?>
    <div class="page-header">
      <h1>Cargos</h1>
    </div>
    <div class="middle-content">
        <?php
            $thead = '  <tr>
                            <th width="100">Código</th>
                            <th width="40">Cargo</th>
                            <th width="160">Setor</th>
                            <th width="180">Ações</th>
                        </tr>';
            $tfoot = '  <tr>
                            <th>Código</th>
                            <th>Cargo</th>
                            <th>Setor</th>
                            <th>Ações</th>
                        </tr>';  
                $tbody = '';
                foreach ($cargos as $cargo):

            $tbody .='  <tr id="'.$cargo->getId().'">
                            <td>'.$cargo->getId().'</td>
                            <td>'.$cargo->getNome().'</td>
                            <td>'.$cargo->getSetor().'</td>
                            <td>'
                                .$this->templateFactory->getButton('editar',array('href'=> URL.'funcionarios/cargos/gerenciar/editar/'.$cargo->getId()))
                                .$this->templateFactory->getButton('excluir', array('id'=> $cargo->getId())).
                            '</td>
                        </tr>';
                endforeach;
                echo $template->getTable('tabela', array('thead'=>$thead, 'tfoot'=>$tfoot, 'tbody'=>$tbody));
            
            ?>



        
    </div>

</div>

<script type="text/javascript">
    $(function(){
        //DATATABLE
        var table = $('.dataTable').DataTable({
            order: [0,'asc']
        });

        //EXCLUIR
        table.$('.btn_excluir').on('click',function(){
            var id = $(this).attr('id');
            var status = $(this).data('value');
            var modalDelete = $('#modalDelete').modal('show')
            $('.btn_ok','#modalDelete').on('click', function(event) {
                $.post(url+'funcionarios/cargos/gerenciar/excluir',{id:id,status:status},function(data){
                    console.log(data)
                    if(data == true){
                        $('#modalDelete').modal('hide');
                        $('tr#'+id).hide();
                    }
                });
            });
        });


    })
</script>

