	<div class="container">
    <?php

    // if($nivel->getPermissoes() == '*' || $nivel->getPermissoes() == null)
    //     $permissao = array();
    // else
    //     $permissao = json_decode(($nivel->getPermissoes()->getP),true);

    $permissao = $nivel->getPermissoes();
    // echo '<pre>';
    // print_r($permissao);
    // echo '</pre>';
    ?>
    <div class="page-header">
      <h1>Níveis de acesso <small><?=$nivel->getNome()?></small></h1>
    </div>
    <div class="text-left list_grupo_usuario" >
        <form action="<?=URL?>configuracoes/niveis_acesso/gerenciar/atualizar" id="form_nivel_acesso" method="POST">


            <button class="btn btn-defult checkAll">Selecionar todos</button><button class="btn btn-defult uncheckAll">Remover seleção</button>
            <div class="input-group">
                <span class="input-group-addon">
                    <input type="checkbox" name="administrador" value="*" <?=$nivel->getPermissoes() == '*' ? 'checked="checked"' : ''?> >
                </span>
                <input type="text" class="form-control" placeholder="Administrador" value="Administrador" disabled="disabled">
            </div>
            <div class="tree" style="padding-top: 14px;padding-right: 14px;">
            <?php
            if(!empty($nivel->getPermissoes())):
            ?>
                <ul>
                <?php
                foreach ($nivel->getPermissoes() as $keyMod => $mod):
                    $checked = '';
                    if($mod->getAcesso())
                        $checked = 'checked="checked"';
                ?>
                    <li><!--modulo-->
                        <div class="form-group has-feedback">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <input type="checkbox" name="status" id="<?=$mod->getId()?>" mod-pai="0" tipo="modulo" campo="status_modulo" url="<?=$mod->getUrl()?>" <?=$checked?>>
                                </span>
                                <input type="text" class="form-control" placeholder="<?=$mod->getUrl()?>" value="<?=$mod->getNome()?>" tipo="modulo" id="<?=$mod->getId()?>" campo="nome_modulo" disabled>
                            </div>
                        </div>
                        <?php
                        if(!empty($mod->getPaginas())):
                        ?>
                        <ul>
                            <?php
                            foreach ($mod->getPaginas() as $keyModPag => $modPag):
                                $checked = '';
                                if($modPag->getAcesso())
                        			$checked = 'checked="checked"';
                            ?>
                            <li>
                                <div class="form-group has-feedback">
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <input type="checkbox" name="status" id="<?=$modPag->getId()?>" tipo="pagina" campo="status_pagina" url="<?=$modPag->getUrl()?>" <?=$checked?>>
                                        </span>
                                        <input type="text" class="form-control" placeholder="<?=$modPag->getUrl()?>" value="<?=$modPag->getNome()?>" tipo="pagina" id="<?=$modPag->getId()?>" campo="nome_pagina" disabled>
                                    </div>
                                </div>
                                <?php
                                if(!empty($modPag->getActions())):
                                ?>
                                <ul>
                                    <?php

                                    foreach ($modPag->getActions() as $keyModPagAct => $modPagAct):
                                        $checked = '';
                                        if($modPagAct->getAcesso())
                        					$checked = 'checked="checked"';
                                    ?>
                                    <li>
                                        <div class="form-group has-feedback">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <input type="checkbox" name="status" id="<?=$modPagAct->getId()?>" tipo="acao" campo="status_action" url="<?=$modPagAct->getUrl()?>" <?=$checked?>>
                                                </span>
                                                <input type="text" class="form-control" placeholder="<?=$modPagAct->getUrl()?>" value="<?=$modPagAct->getNome()?>" tipo="acao" id="<?=$modPagAct->getId()?>" campo="nome_action" disabled>
                                            </div>
                                        </div>
                                    </li>
                                    <?php
                                    endforeach;
                                    ?>
                                </ul>
                                <?php
                                endif;
                                ?>



                            </li>
                            <?php
                            endforeach;
                            ?>
                        </ul>
                        <?php
                        endif;
                        ?>




                        <?php
                        if(!empty($mod->getModulos())):
                            
                        ?>
                        <ul>
                            <?php
                            foreach ($mod->getModulos() as $keyModSubmod => $modSubmod):
                                $checked = '';
                                if($modSubmod->getAcesso())
                        			$checked = 'checked="checked"';
                            ?>
                            <li>
                                <div class="form-group">
                                    <div class="input-group has-feedback">
                                        <span class="input-group-addon">
                                            <input type="checkbox" name="status" id="<?=$modSubmod->getId()?>" tipo="submodulo" campo="status_modulo" url="<?=$modSubmod->getUrl()?>" <?=$checked?>>
                                        </span>
                                        <input type="text" class="form-control" placeholder="<?=$modSubmod->getUrl()?>" value="<?=$modSubmod->getNome()?>" tipo="submodulo" id="<?=$modSubmod->getId()?>" campo="nome_modulo" disabled>
                                    </div>
                                </div>
                                <?php
                                if(!empty($modSubmod->getPaginas())):
                                ?>
                                <ul>
                                    <?php
                                    foreach ($modSubmod->getPaginas() as $keyModSubmodPag => $modSubmodPag):
                                        $checked = '';
                                        if($modSubmodPag->getAcesso())
                        					$checked = 'checked="checked"';
                                    ?>
                                    <li>
                                        <div class="form-group has-feedback">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <input type="checkbox" name="status" id="<?=$modSubmodPag->getId()?>" tipo="pagina" campo="status_pagina" url="<?=$modSubmodPag->getUrl()?>" <?=$checked?> >
                                                </span>
                                                <input type="text" class="form-control" placeholder="<?=$modSubmodPag->getUrl()?>" value="<?=$modSubmodPag->getNome()?>" tipo="pagina" id="<?=$modSubmodPag->getId()?>" campo="nome_pagina" disabled>
                                            </div>
                                        </div>

                                        <?php
                                        if(!empty($modSubmodPag->getActions())):
                                        ?>
                                        <ul>
                                            <?php
                                            foreach ($modSubmodPag->getActions() as $keyModSubmodPagAct => $modSubmodPagAct):
                                                $checked = '';
                                                if($modSubmodPagAct->getAcesso())
                        							$checked = 'checked="checked"';
                                            ?>
                                            <li>
                                                <div class="form-group has-feedback">
                                                    <div class="input-group">
                                                        <span class="input-group-addon">
                                                            <input type="checkbox" name="status" id="<?=$modSubmodPagAct->getId()?>" tipo="acao" campo="status_action" url="<?=$modSubmodPagAct->getUrl()?>" <?=$checked?> >
                                                        </span>
                                                        <input type="text" class="form-control" placeholder="<?=$modSubmodPagAct->getUrl()?>" value="<?=$modSubmodPagAct->getNome()?>" tipo="acao" id="<?=$modSubmodPagAct->getId()?>" campo="nome_action" disabled> 
                                                    </div>
                                                </div>
                                            </li>
                                            <?php
                                            endforeach;
                                            ?>
                                        </ul>
                                        <?php
                                        endif;
                                        ?>


                                    </li>
                                    <?php
                                    endforeach;
                                    ?>
                                </ul>
                                <?php
                                endif;
                                ?>
                            </li>
                            <?php
                            endforeach;
                            ?>
                        </ul>
                        <?php
                        endif;
                        ?>
                    </li>
                <?php
                endforeach;
                ?>

                </ul>
            <?php
            endif;
                
            ?>
            </div>
            <input type="hidden" name="id_nivel" value="<?=$nivel->getId()?>">
            <input type="submit" name="btn_salvar" value="Salvar" class="btn btn-default text-right" style="float:right"/>
        </form>
    </div>
</div>
<style>
.popover-content {
  padding: 0px 0px;
}
</style>
<script type="text/javascript" src="<?=URL?>skin/js/jquery-tree/js/jquery.tree.js"></script>
<link rel="stylesheet" type="text/css" href="<?=URL?>skin/js/jquery-tree/css/jquery.tree.css"/>
<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<script>
$(function() {   
     $('#form_nivel_acesso').submit(function(e) { 

        var modulos = Object();

        //pegando os modulos
        $('.tree>ul>li').each(function(){
            if($('input[type=checkbox]:checked',this).is(':checked'))
            {
                var auxMod = Object();
                var auxPag = Object();
                //pegando os submodulos
                $('>ul>li',this).each(function(){
                    if($('input[type=checkbox]:checked',this).is(':checked') && $('input[type=checkbox]:checked',this).attr('tipo') == 'submodulo')
                    {
                        var aux2 = Object();
                        //pegando as paginas
                        $('>ul>li',this).each(function(){
                            if($('input[type=checkbox]:checked',this).is(':checked'))
                            {
                                var aux3 = Object();
                                //pegando as actions
                                $('>ul>li',this).each(function(){
                                    if($('input[type=checkbox]:checked',this).is(':checked')){
                                        aux3[$('input[type=checkbox]:checked',this).attr('id')] = ''
                                    }
                                });
                                aux2[$('input[type=checkbox]:checked',this).attr('id')] = aux3;
                            }
                        });
                        auxMod[$('input[type=checkbox]:checked',this).attr('id')] = aux2;
                    }else
                    if($('input[type=checkbox]:checked',this).is(':checked') && $('input[type=checkbox]:checked',this).attr('tipo') == 'pagina')
                    {
                        var auxAction = Object();
                        //pegando as actions
                        $('>ul>li',this).each(function(){
                            if($('input[type=checkbox]:checked',this).is(':checked')){
                                auxAction[$('input[type=checkbox]:checked',this).attr('id')] = '';
                            }
                        });
                        auxPag[$('input[type=checkbox]:checked',this).attr('id')] = auxAction

                    }
                });

                modulos[$('input[type=checkbox]:checked',this).attr('id')] = {
                                                                                'submodulos' : auxMod,
                                                                                'paginas' : auxPag
                                                                                };

                console.log(modulos)
            }
        });


        modulos = JSON.stringify(modulos);

        var sendInfo = {
            'permissoes' : modulos,
            'id' : $('input[name=id_nivel]').val()
        }
        
        //console.log(sendInfo);
  

        //console.log(sendInfo)
        $(this).uploadForm({
            'parameters': sendInfo,
            'reload' : true,
            'resetform':false
            //'redirect' : '<?=URL?>configuracoes/usuarios/grupo_usuarios' 
        });
     
        return false;
    });





    $('.tree').tree({
        collapseUiIcon: 'ui-icon-plus',
        expandUiIcon: 'ui-icon-minus',
        leafUiIcon: 'ui-icon-bullet'
    });

    $('.checkAll').click(function(){
        $('.tree').tree('checkAll');
        return false;
    });

    $('input[name=administrador]').change(function(){
        if($(this).is(':checked'))
            $('.tree').tree('checkAll');
        else
            $('.tree').tree('uncheckAll');
    });

    $('input[name=status]').change(function(){
        var stCheck = 0;
        $('input[name=status]').each(function(index, el) {
            if(!$(el).is(':checked'))
               stCheck++;
        });

        if(stCheck == 0)
            $('input[name=administrador]').prop( "checked", true );
        else
            $('input[name=administrador]').prop( "checked", false );
        console.log(stCheck)
    });

    $('.uncheckAll').click(function(){
        $('.tree').tree('uncheckAll');
        return false;
    });

 $('.ui-icon-minus').trigger('click')

});
</script>