<table class="dataTable rwd-table" cellspacing="0" width="100%" style="display:none">
    <thead>
        <tr>
            <th width="30">Id</th>
            <th width="30">Fornecedor</th>
            <th width="300">Titulo</th>
            <th width="300">Data</th>
            <th width="80">Ações</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td>Id</td>
            <td>Fornecedor</td>
            <th>Titulo</th>
            <th>Data</th>
            <td>Ações</td>
        </tr>
    </tfoot>
    <tbody>
        <?php foreach ($compromissosagendados as $compromissos):?>
        <tr id="<?=$compromissos->getId()?>">
            <td><?=$compromissos->getId()?></td>
            <td><?=$compromissos->getFornecedor()->getNomeFantasia()?></td>
            <td><?=$compromissos->getTitulo()?></td>
            <td><input type="date" iddata="<?=$compromissos->getId()?>" name="dataAgenda" min="<?=$compromissos->getData()?>" disabled value="<?=$compromissos->getData()?>" /></td>
            <td>
                <?=$this->templateFactory->getButton('Adiar', array('href'=>URL.'agenda/gerenciar/adiarCompromissos/'.$compromissos->getId(), 'title'=>'Adiar', 'moreContent'=>' habilitar iddata="'.$compromissos->getId().'"'))?>
            </td>
        </tr>
        <?php endforeach;?>  
    </tbody>
</table>
<script type="text/javascript" src="<?=URL?>skin/js/agenda/compromissosagendados.js"></script>

