<div class="container">
    <?php
        $btnCadastrarFunc = $this->templateFactory->getButton("cadastrar",array('href'=>URL.'funcionarios/grupo_funcionarios/gerenciar/cadastrar/funcionarios','title'=>'Grupo de Funcionários'));
        $btnCadastrarGere = $this->templateFactory->getButton("cadastrar",array('href'=>URL.'funcionarios/grupo_funcionarios/gerenciar/cadastrar/gerente','title'=>'Grupo de Gerente'));
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnCadastrarFunc.$btnCadastrarGere));

    ?>
    <div class="page-header">
      <h1>Grupos de permissões de funcionários e gerentes</h1>
    </div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="middle-content">

        <?php
        
        $thead = '  <tr>
                        <th>Nome</th>
                        <th width="180">Ações</th>
                    </tr>';
        $tfoot = '  <tr>
                        <th>Nome</th>

                        <th>Ações</th>
                    </tr>';	 

        $tbody = '';
        foreach ($gruposFuncionarios as $grupo):
            $tbody .='  <tr id="'.$grupo->getId().'">
                            <td>'.$grupo->getNome().'</td>
                            <td>
                                '
                                .$this->templateFactory->getButton('editar',array('href'=> URL.'funcionarios/grupo_funcionarios/gerenciar/editar/'.$grupo->getNivel()->getIndice().'/'.$grupo->getId()))
                                .$this->templateFactory->getButton('excluir', array('id'=> $grupo->getId())).

                            '</td>
                        </tr>';
        endforeach;
        echo $template->getTable('tabela', array('thead'=>$thead, 'tfoot'=>$tfoot, 'tbody'=>$tbody));
       ?>
    </div>

</div>
</div>
<script>
$(document).ready(function() {
    var table = $('.dataTable').DataTable({
    	order: []
    });
    table.$('.btn_excluir').on('click',function(){
        var id = $(this).attr('id');
        var status = 'Excluído';

        $("#dialogResult").html('Deseja mesmo excluir?');
		$("#dialogResult").dialog({
			autoOpen: true,
			buttons: [
				{
					text: "Ok",
					click: function() {
						$( this ).dialog( "close" );

				    	$.post(url+'funcionarios/grupo_funcionarios/gerenciar/excluir',{id:id,status:status},function(data){
							 console.log(data);
                            if(data == true)
								$('tr#'+id).hide();
						});
					}
				},
				{
					text: "Cancelar",
					click: function() {
						$( this ).dialog( "close" );
					}
				}
			]
		});



		
        
    });

    table.$('input[name=status]').on('change',function(){
    	var id = $(this).attr('id')
    	var status = 'Inativo';
		if($(this).is(':checked'))
			status = 'Ativo';

		$.post(url+'configuracoes/tabelas/usuario/atualizarStatus',{id:id,status:status},function(data){

		})

    });


});
</script>