<div class="container">
    <?php
    $btnVoltar = $this->templateFactory->getButton('voltar',array('href'=>URL.'produtos/gerenciar'));
    echo $this->templateFactory->getButton('actions_buttons',array('buttons'=>$btnVoltar));
    ?>
    <div class="page-header">
        <h1>Produtos<small> Cadastro</small></h1>
    </div>
    <form action="<?=URL?>produtos/gerenciar/inserir" method="post" id="form_produto">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Gerais</div>
            <div class="panel-body">

                <div class="row col-xs-12 col-md-3 col-sm-3 col-lg-3">
                    <div class="col-xs-12 col-md-12">
                        <label for="foto" class="inputFoto preview-lg">
                            <div class="thumbnail img-preview preview-lg">
                                <img src="<?=URL?>skin/img/imagens/forn.jpg" id="img_previous">
                            </div>
                            <input type="file" name="foto" id="foto" accept="image/*">
                        </label>
                    </div>
					<div class="col-xs-12 col-md-12">
						<div class="form-group">
							<div class="thumbnail preview-lg">
								<lable>Código de barras (GTI)</lable>
								<input type="text" id="barCodeGti" name="codigobarras" class="form-control " value="" maxlength="13" placeholder="cod. de barras" />
								<div class="demo-section k-content box-barcode-produto">
						            <div id="barcode"></div>
						        </div>
					        </div>
	                    </div>
					</div>
					

                </div>
                <div class="row col-xs-6 col-md-3 col-sm-9 col-lg-9">
                    <div class="form-group col-xs-12 col-md-6 col-sm-4 col-lg-4">
                        <label>Nome</label>
                        <input type="text" class="form-control" placeholder="Nome" aria-describedby="basic-addon1" name="nome">
                    </div>

                    <div class="form-group col-xs-12 col-md-6 col-sm-4 col-lg-4">
                        <label>Marca</label>
                        <select name="marca" id="marca" class="form-control">
                            <option selected="selected" disabled="disabled" value="">..Selecione..</option>
                            <?php if(!empty($marcas)):?>
                            <?php foreach ($marcas as $marcas):?>
                            <option value="<?= $marcas->getId()?>"><?= $marcas->getNome()?></option>
                            <?php endforeach;?>
                            <?php endif;?>
                        </select>
                    </div>
                    <div class="form-group col-xs-12 col-md-6 col-sm-4 col-lg-4">
                        <label>Categoria</label>
                        <select name="categoria" id="categoria" class="form-control">
                            <option selected="selected" disabled="disabled" value="">..Selecione..</option>
                            <?php if(!empty($categorias)):?>
                            <?php foreach ($categorias as $categorias):?>
                            <option value="<?= $categorias->getId()?>"><?= $categorias->getNome()?></option>
                            <?php endforeach;?>
                            <?php endif;?>
                        </select>
                    </div>
	                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-4">
	                    <label>Preço padrão</label>
	                    <input type="text" class="form-control" placeholder="Preço" name="preco" >
	                </div>
	                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-4">
						<lable>Controlar validade</lable>
						<select name="controlarvalidade" class="form-control">
							<option value="1">Sim</option>
							<option value="0">Não</option>
						</select>
					</div>
                    <div class="form-group col-xs-12 col-md-12 col-sm-12 col-lg-12">
                        <label>Descrição</label>
                        <textarea class="form-control" placeholder="Descrição" name="descricao"></textarea>
                    </div>

                   <div class="form-group col-xs-12 col-md-12 col-sm-12 col-lg-12">
                        <label>Fornecedor</label>
                        <div class="input-group">
	                        <select name="listafornecedores" class="form-control">
	                            <?php if(!empty($fornecedores)):?>
	                            <?php foreach ($fornecedores as $fornecedores):?>
	                            <option value="<?= $fornecedores->getId()?>" foto="<?= ($fornecedores->getFoto() != '') ? URL.'skin/uploads/fornecedores/p/'.$fornecedores->getFoto() : URL.'skin/img/imagens/semlogo.jpg'?>" nome="<?=$fornecedores->getNomeFantasia()?>"><?= $fornecedores->getNomeFantasia()?></option>
	                            <?php endforeach;?>
	                            <?php endif;?>
	                        </select>
	                        <span class="input-group-addon" id="basic-addon1"><a href="javascript:void(0)" class="addFornecedor"><span class="glyphicons glyphicons-plus"></span></a></span>
	                   	</div>
                    </div>

                    <div class="listFornecedores">
                    </div>
                </div>
            </div> 

        </div> <!-- fim panel dados gerais -->
        
        <!--UNIDADE MEDIDA ESTOQUE-->
        <div class="panel panel-default">
            <div class="panel-heading">
                Unidades de medida (controle de estoque)
                <div class="pull-right">
                    <a href="javascript:void(0)" class="btn btn-primary btn-sm btn_addUnidade">Adicionar</a>
                </div> 
            </div>
            <div class="panel-body">
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>Atenção!</strong> A primeira unidade refere-se a unidade de venda, o fator das demais unidades corresponde ao fator de venda.
                </div>
                <div class="row groupUnidades">
                </div>
            </div>
        </div>


        

		
        <div class="btn-group pull-right" role="group">
            <button type="submit" class="btn btn-success">Enviar</button>
        </div>
    </form>
</div>


<div class="col-sm-6 col-md-3 col-lg-3 modeloFornecedor hide" id="">
	<input type="hidden" name="idFornecedorProduto" value="">
	<input type="hidden" name="idFornecedor">    
	<div class="thumbnail">
      	<img src="<?=URL?>skin/img/imagens/semlogo.jpg" class="fotoFornecedor">
      	<div class="caption">
         	<div class="form-group">
            	<label id="nomeFornecedor">Fornecedor</label>
          	</div>
          	<p><a href="javascript:void(0)" class="btn btn-danger removeFornecedor" id="" role="button">Remover</a></p>
        </div>
   	</div>
</div>


<div class="col-sm-6 col-md-3 modeloUnidadeMedida hide">
    <input type="hidden" name="idUnidadeMedidaProduto" value="">
    <div class="thumbnail">
        <div class="caption">
            <div class="form-group">
                <label>Uni. medida</label>
                
                <select name="unidadeMedida" class="form-control">
                <?php foreach ($unidademedida as $unidade):?>
                    <option value="<?=$unidade->getId()?>"><?=$unidade->getNome()?></option>
                <?php endforeach;?>
                </select>
            </div>
            <div class="form-group">
                <label>Fator conversão</label>
                <input type="text" value="1" class="form-control" placeholder="Fator" name="fator_unidade" maxlength="20" value="1">
            </div>
            <fieldset class="form-group">
                <div class="input-group">
			      	<label class="input-group-addon">
			        	<input type="radio" name="venda" value="" disabled="disabled">
			      	</label>
			      	<p class="form-control">Saída p/ cada venda</p>
			    </div><!-- /input-group -->
				
				<div class="input-group">
			      	<label class="input-group-addon">
			        	<input type="radio" name="estoque" value="" >
			      	</label>
			      	<p class="form-control">Controle de estoque</p>
			    </div><!-- /input-group -->

            </fieldset>
            <p><a href="javascript:void(0)" class="btn btn-danger btn_removeUnidMed" role="button">Excluir</a></p>
        </div>
    </div>
</div>


<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<link href="<?=URL?>skin/js/croper/cropper.min.css" rel="stylesheet">
<link href="<?=URL?>skin/js/croper/main.css" rel="stylesheet">
<script src="<?=URL?>skin/js/croper/cropper.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskMoney.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/produtos/cadastrar.js"></script>