<div class="container">
    <?php
    $dataformat = new dataformat();
    $btnVoltar = $this->templateFactory->getButton('voltar',array('href'=>URL.'produtos/gerenciar'));
    echo $this->templateFactory->getButton('actions_buttons',array('buttons'=>$btnVoltar));
    ?>
    <div class="page-header">
        <h1>Produtos<small> Editar</small></h1>
    </div>
    <form action="<?=URL?>produtos/gerenciar/atualizar" method="post" id="form_produto">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Gerais</div>
            <div class="panel-body">

                <div class="row col-xs-12 col-md-3 col-sm-3 col-lg-3">
                    <div class="col-xs-12 col-md-12">
                        <label for="foto" class="inputFoto preview-lg">
                            <div class="thumbnail img-preview preview-lg">
                            	<?php
		                        $foto = $produto->getFoto() != '' ? URL.'skin/uploads/produtos/p/'.$produto->getFoto(): URL.'skin/img/imagens/forn.jpg';
		                        ?>
                                <img src="<?=$foto?>" id="img_previous">
                            </div>
                            <input type="file" name="foto" id="foto" accept="image/*">
                            <input type="hidden" name="nome_foto" value="<?=$produto->getFoto()?>">
                            
                        </label>
                    </div>
                    <div class="col-xs-12 col-md-12">
                        <div class="form-group">
                            <div class="thumbnail preview-lg">
                                <lable>Código de barras (GTI)</lable>
                                <input type="text" id="barCodeGti" name="codigobarras" class="form-control " value="<?=$produto->getCodigoBarra()?>" maxlength="13" placeholder="cod. de barras" />
                                <div class="demo-section k-content box-barcode-produto">
                                    <div id="barcode"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    

                </div>
                <div class="row col-xs-6 col-md-3 col-sm-9 col-lg-9">
                    <div class="form-group col-xs-12 col-md-6 col-sm-4 col-lg-4">
                        <label>Nome</label>
                        <input type="text" class="form-control" placeholder="Nome" aria-describedby="basic-addon1" name="nome" value="<?=$produto->getNome()?>">
                    </div>

                    <div class="form-group col-xs-12 col-md-6 col-sm-4 col-lg-4">
                        <label>Marca</label>
                        <select name="marca" id="marca" class="form-control">
                            <option selected="selected" disabled="disabled" value="">..Selecione..</option>
                            <?php if(!empty($marcas)):?>
                            <?php foreach ($marcas as $marcas):?>
                            <option value="<?= $marcas->getId()?>" <?=($produto->getMarca()->getId() == $marcas->getId()) ? 'selected="selected"' : ''?> ><?= $marcas->getNome()?></option>
                            <?php endforeach;?>
                            <?php endif;?>
                        </select>
                    </div>
                    <div class="form-group col-xs-12 col-md-6 col-sm-4 col-lg-4">
                        <label>Categoria</label>
                        <select name="categoria" id="categoria" class="form-control">
                            <option selected="selected" disabled="disabled" value="">..Selecione..</option>
                            <?php if(!empty($categorias)):?>
                            <?php foreach ($categorias as $categoria):?>
                             <option value="<?= $categoria->getId()?>" <?=($produto->getCategoria()->getId() == $categoria->getId()) ? 'selected="selected"' : ''?>><?= $categoria->getNome()?></option>
                            <?php endforeach;?>
                            <?php endif;?>
                        </select>
                    </div>
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-4">
                        <label>Preço padrão</label>
                        <input type="text" class="form-control" placeholder="Preço" name="preco" value="<?=$dataformat->formatar($produto->getPrecoPadrao()->getPreco(), 'decimal')?>">
                    </div>
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-4">
                        <lable>Controlar validade</lable>
                        <select name="controlarvalidade" class="form-control">
                            <option value="1" <?=($produto->getControleValidade()) ? 'selected="selected"' : ''?>>Sim</option>
                            <option value="0" <?=(!$produto->getControleValidade()) ? 'selected="selected"' : ''?>>Não</option>
                        </select>
                    </div>
                    <div class="form-group col-xs-12 col-md-12 col-sm-12 col-lg-12">
                        <label>Descrição</label>
                        <textarea class="form-control" placeholder="Descrição" name="descricao"><?=$produto->getDescricao()?></textarea>
                    </div>

                    <div class="form-group col-xs-12 col-md-12 col-sm-12 col-lg-12">
                        <label>Fornecedor</label>
                        <div class="input-group">
                            <select name="listafornecedores" class="form-control">
                                <?php if(!empty($fornecedores)):?>
                                <?php foreach ($fornecedores as $fornecedores):?>
                                <option value="<?= $fornecedores->getId()?>" foto="<?= ($fornecedores->getFoto() != '') ? URL.'skin/uploads/fornecedores/p/'.$fornecedores->getFoto() : URL.'skin/img/imagens/semlogo.jpg'?>" nome="<?=$fornecedores->getNomeFantasia()?>"><?= $fornecedores->getNomeFantasia()?></option>
                                <?php endforeach;?>
                                <?php endif;?>
                            </select>
                            <span class="input-group-addon" id="basic-addon1"><a href="javascript:void(0)" class="addFornecedor"><span class="glyphicons glyphicons-plus"></span></a></span>
                        </div>
                    </div>

                    <div class="listFornecedores">
                    	<?php foreach($produto->getFornecedores() as $fornecedor):?>
                    	<div class="col-sm-6 col-md-3 col-lg-3 group_fornecedor" id="<?=$fornecedor->getFornecedor()->getId()?>">
						    <input type="hidden" name="idFornecedorProduto" value="<?=$fornecedor->getId()?>">
						    <input type="hidden" name="idFornecedor" value="<?=$fornecedor->getFornecedor()->getId()?>">    
						    <div class="thumbnail">
						        <img src="<?= ($fornecedor->getFornecedor()->getFoto() != '') ? URL.'skin/uploads/fornecedores/p/'.$fornecedor->getFornecedor()->getFoto() : URL.'skin/img/imagens/semlogo.jpg'?>" class="fotoFornecedor">
						        <div class="caption">
						            <div class="form-group">
						                <label id="nomeFornecedor"><?=$fornecedor->getFornecedor()->getNomeFantasia()?></label>
						            </div>
						            <p><a href="javascript:void(0)" class="btn btn-danger removeFornecedor" id="<?=$fornecedor->getFornecedor()->getId()?>" role="button">Remover</a></p>
						        </div>
						    </div>
						</div>
						<?php endforeach;?>
                    </div>
                </div>
            </div>

        </div> <!-- fim panel dados gerais -->
        
        <!--UNIDADE MEDIDA ESTOQUE-->
        <div class="panel panel-default">
            <div class="panel-heading">
                Unidades de medida (controle de estoque)
                <div class="pull-right">
                    <a href="javascript:void(0)" class="btn btn-primary btn-sm btn_addUnidade">Adicionar</a>
                </div> 
            </div>
            <div class="panel-body">
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>Atenção!</strong> A primeira unidade refere-se a unidade de venda, o fator das demais unidades corresponde ao fator de venda.
                </div>

                <div class="row groupUnidades">
					<?php foreach($produto->getUnidadeMedidaEstoque() as $key => $unidadeMed):?>
					<div class="col-sm-6 col-md-3 unidMed">
					    <input type="hidden" name="idUnidadeMedidaProduto" value="<?=$unidadeMed->getId()?>">
					    <div class="thumbnail">
					        <div class="caption">
					            <div class="form-group">
					                <label>Uni. medida</label>
					                <select name="unidadeMedida" class="form-control">
					                <?php foreach ($unidademedida as $unidade):?>
					                    <option value="<?=$unidade->getId()?>" <?=($unidadeMed->getUnidadeMedida()->getId() == $unidade->getId()) ? 'selected="selected"' : ''?>><?=$unidade->getNome()?></option>
					                <?php endforeach;?>
					                </select>
					            </div>
					            <div class="form-group">
					                <label>Fator conversão</label>
					                <input type="text" class="form-control" placeholder="Fator" name="fator_unidade" maxlength="20" value="<?=$dataformat->formatar($unidadeMed->getFator(), 'decimalinteiro')?>"  <?=$key == 0 ? 'disabled="disabled"' : ''?>>
					            </div>
					            <fieldset class="form-group">
					                <div class="input-group">
					                    <label class="input-group-addon">
					                        <input type="radio" name="venda" value="" disabled="disabled" <?=($unidadeMed->getParaVenda() == true) ? 'checked="checked"' : ''?>>
					                    </label>
					                    <p class="form-control">Saída p/ cada venda</p>
					                </div><!-- /input-group -->
					                
					                <div class="input-group">
					                    <label class="input-group-addon">
					                        <input type="radio" name="estoque" value="" <?=($unidadeMed->getParaEstoque() == true) ? 'checked="checked"' : ''?>>
					                    </label>
					                    <p class="form-control">Controle de estoque</p>
					                </div><!-- /input-group -->

					            </fieldset>
					            <p><a href="javascript:void(0)" class="btn btn-danger btn_removeUnidMed" role="button">Excluir</a></p>
					        </div>
					    </div>
					</div>
					<?php endforeach;?>

                </div>
            </div>
        </div>


        

        <input type="hidden" name="id_produto" value="<?=$produto->getId()?>">
        <div class="btn-group pull-right" role="group">
            <button type="submit" class="btn btn-success">Enviar</button>
        </div>
    </form>
</div>

<!-- MODELO FORNECEDOR-->
<div class="col-sm-6 col-md-3 col-lg-3 modeloFornecedor hide" id="">
    <input type="hidden" name="idFornecedorProduto" value="">
    <input type="hidden" name="idFornecedor">    
    <div class="thumbnail">
        <img src="<?=URL?>skin/img/imagens/semlogo.jpg" class="fotoFornecedor">
        <div class="caption">
            <div class="form-group">
                <label id="nomeFornecedor">Fornecedor</label>
            </div>
            <p><a href="javascript:void(0)" class="btn btn-danger removeFornecedor" id="" role="button">Remover</a></p>
        </div>
    </div>
</div>

<!-- MODELO UNIDADE MEDIDA-->
<div class="col-sm-6 col-md-3 modeloUnidadeMedida hide">
    <input type="hidden" name="idUnidadeMedidaProduto" value="">
    <div class="thumbnail">
        <div class="caption">
            <div class="form-group">
                <label>Uni. medida</label>
                <select name="unidadeMedida" class="form-control">
                <?php foreach ($unidademedida as $unidade):?>
                    <option value="<?=$unidade->getId()?>"><?=$unidade->getNome()?></option>
                <?php endforeach;?>
                </select>
            </div>
            <div class="form-group">
                <label>Fator conversão</label>
                <input type="text" value="1" class="form-control" placeholder="Fator" name="fator_unidade" maxlength="20" value="1">
            </div>
            <fieldset class="form-group">
                <div class="input-group">
                    <label class="input-group-addon">
                        <input type="radio" name="venda" value="" disabled="disabled">
                    </label>
                    <p class="form-control">Saída p/ cada venda</p>
                </div><!-- /input-group -->
                
                <div class="input-group">
                    <label class="input-group-addon">
                        <input type="radio" name="estoque" value="" >
                    </label>
                    <p class="form-control">Controle de estoque</p>
                </div><!-- /input-group -->

            </fieldset>
            <p><a href="javascript:void(0)" class="btn btn-danger btn_removeUnidMed" role="button">Excluir</a></p>
        </div>
    </div>
</div>


<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<link href="<?=URL?>skin/js/croper/cropper.min.css" rel="stylesheet">
<link href="<?=URL?>skin/js/croper/main.css" rel="stylesheet">
<script src="<?=URL?>skin/js/croper/cropper.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskMoney.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/produtos/editar.js"></script>