<div class="container">
    <?php
       $btnVoltar = $this->templateFactory->getButton("voltar",array('href'=>URL.'produtos/marcas'));
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnVoltar));    ?>
    <div class="page-header">
      <h1>Marca<small> Cadastro</small></h1>
    </div>
    <form action="<?=URL?>produtos/marcas/gerenciar/inserir" method="post" id="form_marca">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Gerais</div>
            <div class="panel-body">

                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Nome</span>
                    <input type="text" class="form-control" placeholder="Nome" name="nome" >
                </div>
                <div class="btn-group pull-right" role="group">
                    <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</button>
                </div>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/produtos/marcas/cadastrar.js"></script>