<table class="dataTable rwd-table" cellspacing="0" width="100%" {{moreContent}} style="display:none">
    <thead>
        {{thead}}
    </thead>
    <tfoot>
        {{tfoot}}
    </tfoot>
    <tbody>
    	{{tbody}}
    </tbody>
</table>

<script type="text/javascript">
	$(function(){
		$(window).load(function() {
			$('#loadTable').hide();
			$('.dataTable').fadeIn();
		});
        if($(this).width() <= '765')
            responsiveTable();
        $(window).resize(function() {
            //console.log($(this).width())
            if($(this).width() <= '765')
                responsiveTable();
            else
                responsiveTableRemove()
        });


        function responsiveTable(){
            var th = Array();
            $('.rwd-table thead th').each(function(){
                th.push($(this).html())
            });

            //console.log(th);
            var i = 0;
            $('.rwd-table tbody td').each(function(a,b){
                if(!$('div',$(this)).hasClass('dataTables-th')){
                    $(this).prepend('<div class="dataTables-th">'+th[i]+'</div>');
                    i++;
                    if(i == th.length)
                        i=0;
                }
            });
        }
        function responsiveTableRemove(){
            $('.rwd-table tbody td .dataTables-th').remove()
        }


	})



</script>