<div class="container">
    <div class="page-header">
      <h1>Home</h1>
    </div>

	<section>
		<div class="row">
			<div class="col-xs-6 col-md-3 col-lg-7">
				<div class="panel panel-default">
					<div class="panel-heading">
					    <h3 class="panel-title">Atalhos</h3>
					</div>
					<div class="panel-body">
					  	<div class="col-xs-6 col-md-3">
					    	<a href="<?=URL?>produtos/gerenciar/cadastrar" class="thumbnail">
					    	  	Cadastro de produtos
					    	</a>
					  	</div>
					  	<div class="col-xs-6 col-md-3">
					    	<a href="<?=URL?>estoque/armazem/gerenciar/entrada" class="thumbnail">
					      		Entrada de mercadorias
					    	</a>
					  	</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-6 col-md-3 col-lg-12">
						<div class="panel panel-default">
							<div class="panel-heading">
							    <h3 class="panel-title">Agendamento pra hoje</h3>
							</div>
							<div class="panel-body" id="compromissoes">

							</div>
						</div>
					</div>
				</div>
				
				
			</div>
			<div class="col-xs-6 col-md-3 col-lg-5">
				<?php if(!empty($produtosBaixos)):?>
				<div class="panel panel-default">
					<div class="panel-heading">
					    <h3 class="panel-title">Produtos com nível baixo</h3>
					</div>
					<div class="panel-body">
						<ul class="list-group">
						<?php
						foreach ($produtosBaixos as $est){
							if($est->getQuantidadeTotal() < $est->getNivelEstoque()->getQuantidadeMinima())
							{
							?>
								<li class="list-group-item"><?=$est->getProduto()->getNome()?> | Qtd.: <?=$est->getQuantidadeTotal()?> <?=$est->getProduto()->getUnidadeMedidaParaEstoque()->getUnidadeMedida()->getNome()?></li>
							<?php
							}
						}
						?>
						</ul>
					</div>
				</div>
				<?php endif;?>
				<div class="row">
					<div class="col-xs-6 col-md-3 col-lg-12">
						<div class="panel panel-default">
							<div class="panel-heading">
							    <h3 class="panel-title">Produtos mais vendidos</h3>
							</div>
							<div class="panel-body" id="compromissoes">
								<div id="chartHome"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<input type="hidden" class="form-control" placeholder="De" name="dataDe" value="01/<?=date('m/Y')?>">
	<input type="hidden" class="form-control" placeholder="Até" name="dataAte" value="31/<?=date('m/Y')?>">
  	<link rel="stylesheet" href="<?=URL?>skin/js/kendoui/css/kendo.common-material.min.css" />
    <link rel="stylesheet" href="<?=URL?>skin/js/kendoui/css/kendo.default.min.css" />
    <script src="<?=URL?>skin/js/kendoui/js/kendo.all.min.js"></script>
    <script src="<?=URL?>skin/js/home.js"></script>
	










 