<div class="container">
    <div class="page-header">
      <h1>Home</h1>
    </div>
<!--     <div id="example">
    <div class="demo-section k-content wide">
        <div id="chart" style="background: center no-repeat url('../content/shared/styles/world-map.png');"></div>
    </div>
    <script>
        function createChart() {
            $("#chart").kendoChart({
                title: {
                    text: "Gross domestic product growth \n /GDP annual %/"
                },
                legend: {
                    position: "bottom"
                },
                chartArea: {
                    background: ""
                },
                seriesDefaults: {
                    type: "line",
                    style: "smooth"
                },
                series: [{
                    name: "India",
                    data: [3.907, 7.943, 7.848, 9.284, 9.263, 9.801, 3.890, 8.238, 9.552, 6.855]
                },{
                    name: "World",
                    data: [1.988, 2.733, 3.994, 3.464, 4.001, 3.939, 1.333, -2.245, 4.339, 2.727]
                },{
                    name: "Russian Federation",
                    data: [4.743, 7.295, 7.175, 6.376, 8.153, 8.535, 5.247, -7.832, 4.3, 4.3]
                },{
                    name: "Haiti",
                    data: [-0.253, 0.362, -3.519, 1.799, 2.252, 3.343, 0.843, 2.877, -5.416, 5.590]
                }],
                valueAxis: {
                    labels: {
                        format: "{0}%"
                    },
                    line: {
                        visible: false
                    },
                    axisCrossingValue: -10
                },
                categoryAxis: {
                    categories: [2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011],
                    majorGridLines: {
                        visible: false
                    },
                    labels: {
                        rotation: "auto"
                    }
                },
                tooltip: {
                    visible: true,
                    format: "{0}%",
                    template: "#= series.name #: #= value #"
                }
            });
        }

        $(document).ready(createChart);
        $(document).bind("kendo:skinChange", createChart);
    </script>

</div>
 -->



 <div id="example">
    <div class="demo-section k-content wide">
        <div id="chart"></div>
    </div>
    <div class="box wide">
        <div class="box-col">
            <h4>Labels Configuration</h4>
            <ul class="options">
                <li>
                    <input id="labels" checked="checked" type="checkbox" autocomplete="off" />
                    <label for="labels">Show labels</label>
                </li>
                <li>
                    <input id="alignCircle" name="alignType" type="radio"
                           value="circle" checked="checked" autocomplete="off" />
                    <label for="alignCircle">Aligned in circle</label>
                </li>
                <li>
                    <input id="alignColumn" name="alignType" type="radio"
                           value="column" autocomplete="off" />
                    <label for="alignColumn">Aligned in columns</label>
                </li>
            </ul>
        </div>
    </div>
    <script>
        function createChart() {
            $("#chart").kendoChart({
                title: {
                    text: "What is you favourite sport?"
                },
                legend: {
                   position: "top"
                },
                seriesDefaults: {
                    labels: {
                        template: "#= category # - #= kendo.format('{0:P}', percentage)#",
                        position: "outsideEnd",
                        visible: true,
                        background: "transparent"
                    }
                },
                series: [{
                    type: "donut",
                    data: [{
                        category: "Football",
                        value: 35
                    }, {
                        category: "Basketball",
                        value: 25
                    }, {
                        category: "Volleyball",
                        value: 20
                    }, {
                        category: "Rugby",
                        value: 10
                    }, {
                        category: "Tennis",
                        value: 10
                    }]
                }],
                tooltip: {
                    visible: true,
                    template: "#= category # - #= kendo.format('{0:P}', percentage) #"
                }
            });
        }

        $(document).ready(function() {
            createChart();
            $(document).bind("kendo:skinChange", createChart);
            $(".box").bind("change", refresh);
        });

        function refresh() {
            var chart = $("#chart").data("kendoChart"),
                pieSeries = chart.options.series[0],
                labels = $("#labels").prop("checked"),
                alignInputs = $("input[name='alignType']"),
                alignLabels = alignInputs.filter(":checked").val();

            chart.options.transitions = false;
            pieSeries.labels.visible = labels;
            pieSeries.labels.align = alignLabels;

            alignInputs.attr("disabled", !labels);

            chart.refresh();
        }
    </script>

</div>

  <link rel="stylesheet" href="<?=URL?>skin/js/kendoui/css/kendo.common-material.min.css" />
    <link rel="stylesheet" href="<?=URL?>skin/js/kendoui/css/kendo.default.min.css" />

    <script src="<?=URL?>skin/js/kendoui/js/kendo.all.min.js"></script>










 