<div class="container">
    <?php
        $btnVoltar = $this->templateFactory->getButton('voltar',array('href'=>URL.'funcionarios/gerenciar'));
        echo $this->templateFactory->getButton('actions_buttons',array('buttons'=>$btnVoltar));
    ?>
    <div class="page-header">
      <h1>Funcionários <small>Cadastro</small></h1>
    </div>
    <form action="<?=URL?>funcionarios/gerenciar/inserir" method="post" id="form_funcionarios">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Gerais</div>
            <div class="panel-body">
                <div class="col-xs-6 col-md-3 col-sm-3 col-lg-3">
                    <label for="foto" class=" inputFoto preview-lg">
                        <div class="thumbnail img-preview preview-lg">
                            <img src="<?=URL?>skin/img/imagens/semfoto.jpg" id="img_previous">
                        </div>
                        <input type="file" name="foto" id="foto" accept="image/*">
                    </label>
                </div>
                
                <div class="col-xs-6 col-md-3 col-sm-3 col-lg-9">
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                        <label>Nome</label>
                        <input type="text" class="form-control" placeholder="Nome" name="nome" >
                    </div>
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                        <label>Sobrenome</label>
                        <input type="text" class="form-control" placeholder="Sobrenome" name="sobrenome">
                    </div>
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                        <label>Data de nascimento</label>
                        <input type="text" class="form-control" placeholder="Data de nascimento" name="dataNascimento">
                    </div>
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                        <label>Sexo</label>
                        <select class="form-control" name="sexo">
                            <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                            <option value="M">Masculino</option>
                            <option value="F">Feminino</option>
                        </select>
                    </div>
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                        <label>RG</label>
                        <input type="text" class="form-control" placeholder="RG" name="rg">
                    </div>
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                        <label>CPF</label>
                        <input type="text" class="form-control" placeholder="CPF" name="cpf">
                    </div>
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                        <label>Estado Civil</label>
                        <select class="form-control" name="estadoCivil">
                            <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                            <option value="Casado">Casado(a)</option>
                            <option value="Solteiro">Solteiro(a)</option>
                            <option value="Divorciado">Divorciado(a)</option>
                            <option value="Viúvo">Viúvo(a)</option>
                        </select>
                    </div>
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                        <label>Escolaridade</label>
                        <select class="form-control" name="escolaridade">
                            <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                            <option value="Ensino Fundamental Incompleto">Ensino Fundamental Incompleto</option>
                            <option value="Ensino Fundamental Completo">Ensino Fundamental Completo</option>
                            <option value="Ensino Médio Incompleto">Ensino Médio Incompleto</option>
                            <option value="Ensino Médio Completo">Ensino Médio Completo</option>
                            <option value="Ensino Superior Incompleto">Ensino Superior Incompleto</option>
                            <option value="Ensino Superior Completo">Ensino Superior Completo</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-heading">Endereço</div>
            <div class="panel-body">
                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>CEP</label>
                    <input type="text" class="form-control" placeholder="CEP" name="cep" id="cep">
                </div>
                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                    <label>Logradouro</label>
                    <input type="text" class="form-control" placeholder="Lougradouro" name="logradouro" id="rua">
                </div>
                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>Número</label>
                    <input type="text" class="form-control" placeholder="Número" name="numero" id="numero">
                </div>
                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>Complemento</label>
                    <input type="text" class="form-control" placeholder="Complemento" name="complemento" id="complemento">
                </div>
                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-5">
                    <label>Bairro</label>
                    <input type="text" class="form-control" placeholder="Bairro" name="bairro" id="bairro">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-5">
                    <label>Cidade</label>
                    <input type="text" class="form-control" placeholder="Cidade" name="cidade" id="cidade">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>UF</label>
                	<select class="form-control" name="estado" id="uf">
                        <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                        <option value="AC">AC - Acre</option>
                        <option value="AL">AL - Alagoas</option>
                        <option value="AP">AP - Amapá</option>
                        <option value="AM">AM - Amazonas</option>
                        <option value="BA">BA - Bahia</option>
                        <option value="CE">CE - Ceará</option>
                        <option value="DF">DF - Distrito Federal</option>
                        <option value="GO">GO - Goiás</option>
                        <option value="ES">ES - Espírito Santo</option>
                        <option value="MA">MA - Maranhão</option>
                        <option value="MT">MT - Mato Grosso</option>
                        <option value="MS">MS - Mato Grosso do Sul</option>
                        <option value="MG">MG - Minas Gerais</option>
                        <option value="PA">PA - Pará</option>
                        <option value="PB">PB - Paraiba</option>
                        <option value="PR">PR - Paraná</option>
                        <option value="PE">PE - Pernambuco</option>
                        <option value="PI">PI - Piauí­</option>
                        <option value="RJ">RJ - Rio de Janeiro</option>
                        <option value="RN">RN - Rio Grande do Norte</option>
                        <option value="RS">RS - Rio Grande do Sul</option>
                        <option value="RO">RO - Rondônia</option>
                        <option value="RR">RR - Roraima</option>
                        <option value="SP">SP - São Paulo</option>
                        <option value="SC">SC - Santa Catarina</option>
                        <option value="SE">SE - Sergipe</option>
                        <option value="TO">TO - Tocantins</option>
                    </select>
                </div>
                
            </div>
        </div><!-- fim panel endereco -->

        <div id="defaultCampos">
            <div class="radio telefones" id="defaultTel" style="margin-bottom:5px;display:none">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <a href="javascript:void(0)" class="delCel pull-right"><span class="glyphicons glyphicons-remove"></span></a>
                        <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                            <label>Categoria</label>
                            <select name="categoria" class="form-control">
                                <option value="telefone" selected="selected">Telefone</option>
                                <option value="celular">Celular</option>
                            </select>
                        </div>
                        <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                            <label>Número</label>
                            <input type="tel" name="telefone" placeholder="Número" class="form-control" />
                        </div>
                        <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                            <label>Operadora</label>
                            <input type="text" name="operadora" placeholder="Operadora" class="form-control" />
                        </div>
                        <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                            <label>Tipo</label>
                            <select name="tipo_telefone" class="form-control">
                                <option value="" selected="selected" disabled="disabled">Selecione um tipo</option>
                                <option value="Pessoal">Pessoal</option>
                                <option value="Residencial">Residencial</option>
                                <option value="Profissional">Profissional</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>

            <div class="radio emails" id="defaultEmail" style="margin-bottom:5px;display:none">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <a href="javascript:void(0)" class="delCel pull-right"><span class="glyphicons glyphicons-remove"></span></a>
                        <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                            <label>Tipo</label>
                            <select name="tipo_email" class="form-control ">
                                <option value="" disabled="disabled">Tipo</option>
                                <option value="Pessoal">Pessoal</option>
                                <option value="Profissional">Profissional</option>
                            </select>
                        </div>
                        <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                            <label>E-mail</label>
                            <input type="email" name="email" placeholder="E-mail" class="form-control" />
                        </div>
                    </div>
                </div>
            </div>

        </div>



        <div class="panel panel-default">
            <div class="panel-heading">Contatos</div>
            <div class="panel-body">
                <div class="form-group group_tel">
                    <button type="button" class="btn btn-default addTel addCel"><span class="glyphicons glyphicons-earphone"></span> Adicionar telefones</button>
                </div>

                <div class="form-group group_email">
                    <button type="button" class="btn btn-default addEmail addCel"><span class="glyphicons glyphicons-envelope"></span> Adicionar E-mail</button>
                </div>
            </div>
        </div>


        <div class="panel panel-default ">
            <div class="panel-heading">Dados Admissionais</div>
            <div class="panel-body">
                <div class="form-group col-xs-6 col-md-3 col-sm-4 col-lg-4">
                    <label>Cargo</label>
                    <select name="cargo" id="cargo" class="form-control">
                        <option selected="selected" disabled="disabled" value="">..Selecione..</option>
                        <?php if(!empty($cargos)):?>
                        <?php foreach ($cargos as $cargo):?>
                        <option value="<?= $cargo->getId()?>"><?=$cargo->getNome()?> - SETOR: <?=$cargo->getSetor()?></option>
                        <?php endforeach;?>
                        <?php endif;?>
                    </select>
                </div>
                <div class="form-group col-xs-6 col-md-3 col-sm-4 col-lg-4">
                    <label>Data De Admissão</label>
                    <input type="text" class="form-control" placeholder="Data De Admissão" name="dataAdmissao">
                </div>
                <div class="form-group col-xs-6 col-md-3 col-sm-4 col-lg-4">
                    <label>Data De Demissão</label>
                    <input type="text" class="form-control" placeholder="Data De Demissão" name="dataDemissao">
                </div>


            </div>
        </div>
        <div class="btn-group pull-right" role="group">
            <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</button>
        </div>
    </form>
</div>

<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<link href="<?=URL?>skin/js/croper/cropper.min.css" rel="stylesheet">
<link href="<?=URL?>skin/js/croper/main.css" rel="stylesheet">
<script src="<?=URL?>skin/js/croper/cropper.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskMoney.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/funcionarios/cadastrar.js"></script>
