<div class="container">
      <?php
        $btnVoltar = $this->templateFactory->getButton('voltar',array('href'=>URL.'funcionarios/gerenciar'));
        echo $this->templateFactory->getButton('actions_buttons',array('buttons'=>$btnVoltar));
        ?>
    <div class="page-header">
      <h1>Funcionários <small>Edição</small></h1>
    </div>
    <form action="<?=URL?>funcionarios/gerenciar/atualizar" method="post" id="form_funcionarios">
        <div class="panel panel-default">
            <div class="panel-heading">Dados Gerais</div>
            <div class="panel-body">
                <div class="col-xs-6 col-md-3">
                    <label for="foto" class="inputFoto preview-lg">
                        <div class="thumbnail img-preview preview-lg">
                        <?php
                        $foto = $funcionario->getFoto() != '' ? URL.'skin/uploads/funcionarios/p/'.$funcionario->getFoto(): URL.'skin/img/imagens/semfoto.jpg';
                        ?>
                            <img src="<?=$foto?>" id="img_previous">
                        </div>
                        <input type="hidden" name="nome_foto" value="<?=$funcionario->getFoto()?>">
                        <input type="file" name="foto" id="foto" accept="image/*">
                    </label>
                </div>
                <div class="col-xs-6 col-md-3 col-sm-3 col-lg-9">
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                        <label>Nome</label>
                        <input type="text" class="form-control" placeholder="Nome" name="nome" value="<?=$funcionario->getNome()?>">
                    </div>
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                        <label>Sobrenome</label>
                        <input type="text" class="form-control" placeholder="Sobrenome" name="sobrenome" value="<?=$funcionario->getSobrenome()?>">
                    </div>
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                        <label>Data de nascimento</label>
                        <input type="text" class="form-control" placeholder="Data de nascimento" name="dataNascimento" value="<?=$dataFormat->formatar($funcionario->getDataNascimento(),'data');?>">
                    </div>

                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                        <label>Sexo</label>
                        <select class="form-control" name="sexo">
                            <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                            <option value="M" <?=$funcionario->getSexo() == 'M' ? 'selected="selected"' : ''?>>Masculino</option>
                            <option value="F" <?=$funcionario->getSexo() == 'F' ? 'selected="selected"' : ''?>>Feminino</option>
                        </select>
                    </div>

                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                        <label>RG</label>
                        <input type="text" class="form-control" placeholder="RG" name="rg" value="<?=$funcionario->getRg()?>">
                    </div>
                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                        <label>CPF</label>
                        <input type="text" class="form-control" placeholder="CPF" name="cpf" value="<?=$funcionario->getCpf()?>">
                    </div> 
                    <div class="form-group col-xs-6 col-md-3 col-sm-6 col-lg-6">
                        <label>Estado Civil</label>
                        <select class="form-control" name="estadoCivil">
                            <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                            <option value="Casado" <?=$funcionario->getEstadoCivil() == 'Casado' ? 'selected="selected"' : ''?>>Casado(a)</option>
                            <option value="Solteiro" <?=$funcionario->getEstadoCivil() == 'Solteiro' ? 'selected="selected"' : ''?>>Solteiro(a)</option>
                            <option value="Divorciado" <?=$funcionario->getEstadoCivil() == 'Divorciado' ? 'selected="selected"' : ''?>>Divorciado(a)</option>
                            <option value="Viúvo" <?=$funcionario->getEstadoCivil() == 'Viúvo' ? 'selected="selected"' : ''?>>Viúvo(a)</option>
                        </select>
                    </div>
                    <div class="form-group col-xs-6 col-md-3 col-sm-6 col-lg-6">
                        <label>Escolaridade</label>
                        <select class="form-control" name="escolaridade">
                            <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                            <option value="Ensino Fundamental Incompleto" <?=$funcionario->getEscolaridade() == 'Ensino Fundamental Incompleto' ? 'selected="selected"' : ''?>>Ensino Fundamental Incompleto</option>
                            <option value="Ensino Fundamental Completo" <?=$funcionario->getEscolaridade() == 'Ensino Fundamental Completo' ? 'selected="selected"' : ''?>>Ensino Fundamental Completo</option>
                            <option value="Ensino Médio Incompleto" <?=$funcionario->getEscolaridade() == 'Ensino Médio Incompleto' ? 'selected="selected"' : ''?>>Ensino Médio Incompleto</option>
                            <option value="Ensino Médio Completo" <?=$funcionario->getEscolaridade() == 'Ensino Médio Completo' ? 'selected="selected"' : ''?>>Ensino Médio Completo</option>
                            <option value="Ensino Superior Incompleto" <?=$funcionario->getEscolaridade() == 'Ensino Superior Incompleto' ? 'selected="selected"' : ''?>>Ensino Superior Incompleto</option>
                            <option value="Ensino Superior Completo" <?=$funcionario->getEscolaridade() == 'Ensino Superior Completo' ? 'selected="selected"' : ''?>>Ensino Superior Completo</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-heading">Endereço</div>
            <div class="panel-body">

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>CEP</label>
                    <input type="text" class="form-control" placeholder="CEP" name="cep" id="cep" value="<?=$funcionario->getEndereco()->getCep()?>">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-6">
                    <label>Logradouro</label>
                    <input type="text" class="form-control" placeholder="Lougradouro" name="logradouro" id="rua"  value="<?=$funcionario->getEndereco()->getLogradouro()?>">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>Número</label>
                    <input type="text" class="form-control" placeholder="Número" name="numero" id="numero"  value="<?=$funcionario->getEndereco()->getNumero()?>">
                </div>
                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>Complemento</label>
                    <input type="text" class="form-control" placeholder="Complemento" name="complemento" id="complemento"  value="<?=$funcionario->getEndereco()->getComplemento()?>">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-5">
                    <label>Bairro</label>
                    <input type="text" class="form-control" placeholder="Bairro" name="bairro" id="bairro"  value="<?=$funcionario->getEndereco()->getBairro()?>">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-5">
                    <label>Cidade</label>
                    <input type="text" class="form-control" placeholder="Cidade" name="cidade" id="cidade"  value="<?=$funcionario->getEndereco()->getCidade()?>">
                </div>

                <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-2">
                    <label>UF</label>
                    <select class="form-control" name="estado" id="uf">
                        <option value="" selected="selected" disabled="disabled">..Selecione..</option>
                        <option value="AC" <?=$funcionario->getEndereco()->getEstado() == 'AC' ? 'selected="selected"' : ''?>>AC - Acre</option>
                        <option value="AL" <?=$funcionario->getEndereco()->getEstado() == 'AL' ? 'selected="selected"' : ''?>>AL - Alagoas</option>
                        <option value="AP" <?=$funcionario->getEndereco()->getEstado() == 'AP' ? 'selected="selected"' : ''?>>AP - Amapá</option>
                        <option value="AM" <?=$funcionario->getEndereco()->getEstado() == 'AM' ? 'selected="selected"' : ''?>>AM - Amazonas</option>
                        <option value="BA" <?=$funcionario->getEndereco()->getEstado() == 'BA' ? 'selected="selected"' : ''?>>BA - Bahia</option>
                        <option value="CE" <?=$funcionario->getEndereco()->getEstado() == 'CE' ? 'selected="selected"' : ''?>>CE - Ceará</option>
                        <option value="DF" <?=$funcionario->getEndereco()->getEstado() == 'DF' ? 'selected="selected"' : ''?>>DF - Distrito Federal</option>
                        <option value="GO" <?=$funcionario->getEndereco()->getEstado() == 'GO' ? 'selected="selected"' : ''?>>GO - Goiás</option>
                        <option value="ES" <?=$funcionario->getEndereco()->getEstado() == 'ES' ? 'selected="selected"' : ''?>>ES - Espírito Santo</option>
                        <option value="MA" <?=$funcionario->getEndereco()->getEstado() == 'MA' ? 'selected="selected"' : ''?>>MA - Maranhão</option>
                        <option value="MT" <?=$funcionario->getEndereco()->getEstado() == 'MT' ? 'selected="selected"' : ''?>>MT - Mato Grosso</option>
                        <option value="MS" <?=$funcionario->getEndereco()->getEstado() == 'MS' ? 'selected="selected"' : ''?>>MS - Mato Grosso do Sul</option>
                        <option value="MG" <?=$funcionario->getEndereco()->getEstado() == 'MG' ? 'selected="selected"' : ''?>>MG - Minas Gerais</option>
                        <option value="PA" <?=$funcionario->getEndereco()->getEstado() == 'PA' ? 'selected="selected"' : ''?>>PA - Pará</option>
                        <option value="PB" <?=$funcionario->getEndereco()->getEstado() == 'PB' ? 'selected="selected"' : ''?>>PB - Paraiba</option>
                        <option value="PR" <?=$funcionario->getEndereco()->getEstado() == 'PR' ? 'selected="selected"' : ''?>>PR - Paraná</option>
                        <option value="PE" <?=$funcionario->getEndereco()->getEstado() == 'PE' ? 'selected="selected"' : ''?>>PE - Pernambuco</option>
                        <option value="PI" <?=$funcionario->getEndereco()->getEstado() == 'PI' ? 'selected="selected"' : ''?>>PI - Piauí­</option>
                        <option value="RJ" <?=$funcionario->getEndereco()->getEstado() == 'RJ' ? 'selected="selected"' : ''?>>RJ - Rio de Janeiro</option>
                        <option value="RN" <?=$funcionario->getEndereco()->getEstado() == 'RN' ? 'selected="selected"' : ''?>>RN - Rio Grande do Norte</option>
                        <option value="RS" <?=$funcionario->getEndereco()->getEstado() == 'RS' ? 'selected="selected"' : ''?>>RS - Rio Grande do Sul</option>
                        <option value="RO" <?=$funcionario->getEndereco()->getEstado() == 'RO' ? 'selected="selected"' : ''?>>RO - Rondônia</option>
                        <option value="RR" <?=$funcionario->getEndereco()->getEstado() == 'RR' ? 'selected="selected"' : ''?>>RR - Roraima</option>
                        <option value="SP" <?=$funcionario->getEndereco()->getEstado() == 'SP' ? 'selected="selected"' : ''?>>SP - São Paulo</option>
                        <option value="SC" <?=$funcionario->getEndereco()->getEstado() == 'SC' ? 'selected="selected"' : ''?>>SC - Santa Catarina</option>
                        <option value="SE" <?=$funcionario->getEndereco()->getEstado() == 'SE' ? 'selected="selected"' : ''?>>SE - Sergipe</option>
                        <option value="TO" <?=$funcionario->getEndereco()->getEstado() == 'TO' ? 'selected="selected"' : ''?>>TO - Tocantins</option>
                    </select>
                    <input type="hidden" name="id_endereco" value="<?=$funcionario->getEndereco()->getId()?>">
                
                </div>
                
            </div>
        </div><!-- fim panel endereco -->

        <div id="defaultCampos">
            <div class="radio telefones" id="defaultTel" style="margin-bottom:5px;display:none">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <a href="javascript:void(0)" class="delCel pull-right"><span class="glyphicons glyphicons-remove"></span></a>
                        <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                            <label>Categoria</label>
                            <select name="categoria" class="form-control">
                                <option value="telefone" selected="selected">Telefone</option>
                                <option value="celular">Celular</option>
                            </select>
                        </div>
                        <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                            <label>Número</label>
                            <input type="tel" name="telefone" placeholder="Número" class="form-control" />
                        </div>
                        <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                            <label>Operadora</label>
                            <input type="text" name="operadora" placeholder="Operadora" class="form-control" />
                        </div>
                        <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                            <label>Tipo</label>
                            <select name="tipo_telefone" class="form-control">
                                <option value="" selected="selected" disabled="disabled">Selecione um tipo</option>
                                <option value="Pessoal">Pessoal</option>
                                <option value="Residencial">Residencial</option>
                                <option value="Profissional">Profissional</option>
                            </select>
                        </div>
                    </div>
                </div>
                <input type="hidden" id="idTelefone" value="">
            </div>

            <div class="radio emails" id="defaultEmail" style="margin-bottom:5px;display:none">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <a href="javascript:void(0)" class="delCel pull-right"><span class="glyphicons glyphicons-remove"></span></a>
                        <div class="form-group col-xs-6 col-md-3 col-sm-6 col-lg-6">
                            <label>Tipo</label>
                            <select name="tipo_email" class="form-control">
                                <option value="" disabled="disabled">Tipo</option>
                                <option value="Pessoal">Pessoal</option>
                                <option value="Profissional">Profissional</option>
                            </select>
                        </div>
                        <div class="form-group col-xs-6 col-md-3 col-sm-6 col-lg-6">
                            <label>E-mail</label>
                            <input type="email" name="email" placeholder="E-mail" class="form-control" />
                        </div>
                        <input type="hidden" id="idTelefone" value="" name="idTelefone">
                    </div>
                </div>
            </div>

        </div>



        <div class="panel panel-default">
            <div class="panel-heading">Contatos</div>
            <div class="panel-body">
                
                <div class="form-group group_tel">
                    <!--TELEFONES-->
                    <?php
                    if(!empty($funcionario->getTelefones())):
                        foreach ($funcionario->getTelefones() as $telefone):
                    ?>
                        <div class="radio telefones" style="margin-bottom:5px;display:block">
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <a href="javascript:void(0)" class="delCel pull-right"><span class="glyphicons glyphicons-remove"></span></a>
                                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                                        <label>Categoria</label>
                                        <select name="categoria" class="form-control">
                                            <option value="telefone" <?=$telefone->getCategoria() == 'telefone' ? 'selected="selected"' : ''?>>Telefone</option>
                                            <option value="celular" <?=$telefone->getCategoria() == 'celular' ? 'selected="selected"' : ''?>>Celular</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                                        <label>Número</label>
                                        <input type="tel" name="telefone" placeholder="Número" class="form-control" value="<?=$telefone->getNumero()?>" />
                                    </div>
                                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                                        <label>Operadora</label>
                                        <input type="text" name="operadora" placeholder="Operadora" class="form-control"  value="<?=$telefone->getOperadora()?>"/>
                                    </div>
                                    <div class="form-group col-xs-6 col-md-3 col-sm-3 col-lg-3">
                                        <label>Tipo</label>
                                        <select name="tipo_telefone" class="form-control">
                                            <option value="" selected="selected" disabled="disabled">Selecione um tipo</option>
                                            <option value="Pessoal" <?=$telefone->getTipo() == 'Pessoal' ? 'selected="selected"' : ''?>>Pessoal</option>
                                            <option value="Residencial" <?=$telefone->getTipo() == 'Residencial' ? 'selected="selected"' : ''?>>Residencial</option>
                                            <option value="Profissional" <?=$telefone->getTipo() == 'Profissional' ? 'selected="selected"' : ''?>>Profissional</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <input type="hidden" id="idTelefone" name="idTelefone" value="<?=$telefone->getId()?>">
                        </div>

                    <?php 
                        endforeach;
                    endif;
                    ?>

                    <button type="button" class="btn btn-default addTel addCel"><span class="glyphicons glyphicons-earphone"></span> Adicionar telefones</button>
                </div>

                <div class="form-group group_email">
                    <!--EMAILS-->
                    <?php
                    if(!empty($funcionario->getEmail())):
                        foreach ($funcionario->getEmail() as $email):
                    ?>
                        <div class="radio emails" style="margin-bottom:5px;display:block">
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <a href="javascript:void(0)" class="delCel pull-right"><span class="glyphicons glyphicons-remove"></span></a>
                                    <div class="form-group col-xs-6 col-md-3 col-sm-6 col-lg-6">
                                        <label>Tipo</label>
                                        <select name="tipo_email" class="form-control">
                                            <option value="" disabled="disabled">Tipo</option>
                                            <option value="Pessoal" <?=$email->getTipo() == 'Pessoal' ? 'selected="selected"' : ''?>>Pessoal</option>
                                            <option value="Profissional" <?=$email->getTipo() == 'Profissional' ? 'selected="selected"' : ''?>>Profissional</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-xs-6 col-md-3 col-sm-6 col-lg-6">
                                        <label>E-mail</label>
                                        <input type="email" name="email" placeholder="E-mail" class="form-control" value="<?=$email->getEmail()?>" />
                                    </div>
                                </div>
                            </div>
                            <input type="hidden" id="idEmail" name="idEmail" value="<?=$email->getId()?>">
                        </div>

                    <?php 
                        endforeach;
                    endif;
                    ?>

                    <button type="button" class="btn btn-default addEmail addCel"><span class="glyphicons glyphicons-envelope"></span> Adicionar E-mail</button>
                </div>
               
            </div>
        </div>


        <div class="panel panel-default ">
            <div class="panel-heading">Dados Admissionais</div>
            <div class="panel-body">

                <div class="form-group col-xs-6 col-md-3 col-sm-4 col-lg-4">
                    <label>Cargo</label>
                    <select name="cargo" id="cargo" class="form-control">
                        <option selected="selected" disabled="disabled" value="">..Selecione..</option>
                        <?php if(!empty($cargos)):?>
                        <?php foreach ($cargos as $cargo):?>
                        <option value="<?= $cargo->getId()?>" <?=($cargo->getId() == $funcionario->getCargo()->getId()) ? 'selected="selected"' : ''?>><?=$cargo->getNome()?> - SETOR: <?=$cargo->getSetor()?></option>
                        <?php endforeach;?>
                        <?php endif;?>
                    </select>
                </div>
                <div class="form-group col-xs-6 col-md-3 col-sm-4 col-lg-4">
                    <label>Data De Admissão</label>
                    <input type="text" class="form-control" placeholder="Data De Admissão" name="dataAdmissao" value="<?=$dataFormat->formatar($funcionario->getDataAdmissao(),'data');?>">
                </div>
                <div class="form-group col-xs-6 col-md-3 col-sm-4 col-lg-4">
                    <label>Data De Demissão</label>
                    <input type="text" class="form-control" placeholder="Data De Demissão" name="dataDemissao" value="<?=$dataFormat->formatar($funcionario->getDataDemissao(),'data');?>">
                </div>
            </div>

        </div>
        <input type="hidden" name="id_funcionario" value="<?=$funcionario->getId()?>">
        <div class="btn-group pull-right" role="group">
            <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Salvar</button>
        </div>

    </form>
</div>
<style type="text/css">
.checkbox+.checkbox, .radio+.radio {
margin-top: 0px;
}
</style>

<script type="text/javascript" src="<?=URL?>skin/js/uploadForm.js"></script>
<link href="<?=URL?>skin/js/croper/cropper.min.css" rel="stylesheet">
<link href="<?=URL?>skin/js/croper/main.css" rel="stylesheet">
<script src="<?=URL?>skin/js/croper/cropper.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskedinput.min.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.maskMoney.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/jquery.validate.js"></script>
<script type="text/javascript" src="<?=URL?>skin/js/funcionarios/editar.js"></script>