<div class="container">
    <?php
        $btnCadastrar = $this->templateFactory->getButton("cadastrar",array('href'=>URL.'funcionarios/gerenciar/cadastrar'), URL.'funcionarios/gerenciar/cadastrar');
        echo $this->templateFactory->getButton("actions_buttons",array('buttons'=>$btnCadastrar));
    ?>
    <div class="page-header">
      <h1>Funcionários</h1>
    </div>
    <div class="middle-content">
        <table class="dataTable rwd-table" cellspacing="0" width="100%" style="display:none">
            <thead>
                <tr>
                    <th width="20">ID</th>
                    <th width="100">Código</th>
                    <th width="40">Foto</th>
                    <th width="160">Nome</th>
                    <th width="160">Cargo</th>
                    <th width="120">CPF</th>
                    <th width="100">Status (Ativo/Inativo)</th>
                    <th width="180">Ações</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>ID</th>
                    <th>Código</th>
                    <th>Foto</th>
                    <th>Nome</th>
                    <th>Cargo</th>
                    <th>CPF</th>
                    <th>Status (Ativo/Inativo)</th>
                    <th>Ações</th>
                </tr>
            </tfoot>
            <tbody>
                <?php
                if(!empty($funcionarios)):
                    foreach ($funcionarios as $func):
                        $foto = $func->getFoto() != '' ? URL.'skin/uploads/funcionarios/p/'.$func->getFoto() : URL.'skin/img/imagens/semfoto.jpg';
                        $ativo = ($func->getStatus() == status::ATIVO) ? 'selected="selected"' : '';
                        $inativo = ($func->getStatus() == status::INATIVO) ? 'selected="selected"' : '';
                ?>        
                    <tr id="<?=$func->getId()?>">
                        <td><?=$func->getId()?></td>
                        <td><?=$func->getCodigo()?></td>
                        <td><img src="<?=$foto?>" style=" width: 60px; height: 60px;" class="img-circle"></td>
                        <td><?=$func->getNome()?> <?=$func->getSobrenome()?></td>
                        <td><?=$func->getCargo()->getNome()?>(<small><?=$func->getCargo()->getSetor()?></small>)</td>
                        <td><?=$func->getCpf()?></td>
                        <td>
                    <?php
                        //permite a mudança de status se nao for administrador
                        if($func->getUsuario() == null || $func->getUsuario()->getNivelAcesso()->getTipoPermissao() == tipopermissao::USUARIO): 
                    ?>
                            <select name="status" id="<?=$func->getId()?>" class="statusSelect">
                                <option value="<?=status::ATIVO?>" class="active" <?=$ativo?>>Ativo</option>
                                <option value="<?=status::INATIVO?>" class="inactive" <?=$inativo?>>Inativo</option>
                            </select>
                    <?php endif; ?>
                        </td>
                        <td>
                            <?=$this->templateFactory->getButton('editar',array('href'=> URL.'funcionarios/gerenciar/editar/'.$func->getId()), URL.'funcionarios/gerenciar/editar/')?>
                            <?php if($func->getUsuario() == null || $func->getUsuario()->getNivelAcesso()->getTipoPermissao() == tipopermissao::USUARIO): //permite a mudança de status se nao for administrador?>
                            <?= $this->templateFactory->getButton('excluir', array('id'=> $func->getId()), URL.'funcionarios/gerenciar/excluir/');?>
                            <?php endif;?>
                        </td>
                    </tr>
                <?php endforeach;
                endif; ?>
            </tbody>
        </table>
            

    </div>

</div>

<script type="text/javascript" SRC="<?=URL?>skin/js/funcionarios/funcionarios.js"></script>