<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>{{assunto}}</title>
  </head>
  <body>
	<table border=0 cellpacing=0 cellpadding=0 style="border:1px solid #CCC; width: 600px;" width="600"> 
		<thead> 
			<tr> 
				<th>
					<img src="http://infodahora.com.br/img/imagens/topo_email.png"> 
				</th>
			</tr>
		</thead>
		<tbody>
			<tr> 
				<td> 
					<h3 style="margin:0;font-size:23px;color:#FFF;background-color:#008fd4;padding:8px;text-align:center;font-family:monospace">{{assunto}}</h3> 
				</td>
			</tr>
			<tr> 
				<td style="font-family:monospace;font-size:14px;padding:5px"> 
					{{mensagem}}
				</td>
			</tr>
			<tr> 
				<td style="padding:0;background-color:#024D82"> 
					<p style="margin:5px;color:#FFF">
						<small>Start Softwares - Prysmarket</small>
					</p>
				</td>
			</tr>
		</tbody> 
	</table>
</body>
</html>
